 **String Based Assignment Problem**




**1**. Write a program to reverse a string.

In [2]:
def reverse_string(input_string):
    return input_string[::-1]

In [3]:
input_string = "Hello World"
reverse_string = reverse_string(input_string)
print("Input_string:",input_string)
print("Reverse string:", reverse_string)

Input_string: Hello World
Reverse string: dlroW olleH


The functiuon reverse_string that takes an input string and return its reverse using([::-1])

2. Check if a string is a palindrome.

In [ ]:
def isPalindrome(input_string):
    cleaned_string= ' '.join(char.lower() for char in input_string if char.isalnum())
    return cleaned_string == cleaned_string[::-1]

In [ ]:
test_string = "I'm Great coder in the world"
result = isPalindrome(test_string)
print(f'the string "{test_string}" is a palindrome: {result}')

the string "I'm Great coder in the world" is a palindrome: False


In [ ]:
test_string = "A man, a plan, a canal, Panama!"
result = isPalindrome(test_string)
print(f'the string "{test_string}" is a palindrome: {result}')

the string "A man, a plan, a canal, Panama!" is a palindrome: True


The function isPalindrome that removes non-alphanumeric character, converts the string to lowercase and then check if it reads the same backward.

3. Convert a string to uppercase.

In [ ]:
input_string = "Gayatri Kale"
uppercase_string = input_string.upper()

print("Input string:",input_string)
print("Uppercase string:", uppercase_string)


Input string: Gayatri Kale
Uppercase string: GAYATRI KALE


input_string = "Gayatri Kale" : the input string the we want to convert to uppercase.

uppercase_string = input_string.uppercase(): upper() can be apply to string to convert then to uppercase.this method is involved input_string, and the result is stored in the variable uppercase_string.

print("Input string:",input_string)
print("Uppercase string:", uppercase_string) : This will display the input string and its uppercase version.


4. Convert a string to lowercase.

In [ ]:
input_string = "GAYATRI KALE"
lowercase_string = input_string.lower()

print("Input string:", input_string)
print("Lowercase string:", lowercase_string)

Input string: GAYATRI KALE
Lowercase string: gayatri kale


input_string = "GAYATRI KALE" : the input string that we want to convert to lowercase.

lowercase_string = input_string.lower() : lower() can be applied to string to convert them to lowercase. This method is involved input_string and the result is stored in the variable lowercase_string.

print("Input string:", input_string)
print("Lowercase string:", lowercase_string): This will display the input string and its lowercase version.

5. Count the number of vowels in a string.

In [4]:
# Declaring the variable to take input from the user.
sentence = input("Enter a sentence:")

# Initialize to zero.
no_vowels = 0

# Specify the vowels that we want to count. Here, we consider both uppercase and lowercase vowels.
vowels = "aeiouAEIOU"

# for loop to iterate though each char in the input string.
for char  in input_string:

    # within the loop, check if each character is vowel by using the in operator to see if it is exists in the vowels string.
    if char in vowels:

        #if character is a vowel, increment the vowel_count variable.
        no_vowels +=1

# Print the input string and the no. of vowels.
print("Number of vowels: ", no_vowels)

Enter a sentence:hello dada
Number of vowels:  3


6. Count the number of consonants in a string.

In [5]:
# Taking the input from the user
sentence = input(" Enter a string:")

# Converting the string to lowercase to ensuring a case insentive count.
lowercase_input = sentence.lower()

#intializing counter
consonant_count = 0

#Iterate through each character in the string and check if it's a consonant.
# This step ensuring that only alphabetic character are considered and vowels are excluded from the count.
for char in lowercase_input:
    if char.isalpha() and char not in "aeiou":
        consonant_count += 1

# Print the total count of consonants.
print("The number of consonants in the string is:",consonant_count)


 Enter a string:raje tumhich
The number of consonants in the string is: 7


7. Remove all whitespaces from a string.

In [ ]:
# Taking the input from the user.
input= " Peter put his phone in his pocket. "

#Using replace method to remove all white spaces from string. This step replaces each space character with an empty string.
no_whitespace = sentence.replace(" ","")

# Print the modified string with no white spaces.
print("string without white spaces:",no_whitespace)

string without white spaces: Peterputhisphoneinhispocket.


8. Find the length of a string without using the `len()` function.

In [ ]:
# Taking input from the users.
input = " Harry has a habit of humming in public."

#Initializing a counter variable to keep track of the length.
length_counter = 0

# Iterating through each char in the string using a for loop.In each iteration,increment the counter.
for char in input:
    length_counter += 1

#Print the calculated length of the string.
print("Length of the string:", length_counter)


Length of the string: 40


9. Check if a string contains a specific word.

In [ ]:
#Taking the input and the specific word to check from the user.
input = "Python is a powerful programming language."
specific_word = "powerful"

#Using in operator to check if the specific word is present in the input string.
#The in operator returns True if the specified word is found in the string, otherwise, it returns False.
contains_word = specific_word in input

                #Print whether the string contains the specific word or not.
if contains_word:
        print(f"The string contains the word '{specific_word}'")
else:
        print(f"The string does not contains the word '{specific_word}'")

The string contains the word 'powerful'


10. Replace a word in a string with another word.

In [ ]:
#Taking input form the user the word to be replaced and the replacement word from the user.
input = "Python is a powerful programming language."
word_to_replace = "powerful"
replacement_word = "great"

#Using the replace method to replace occurances of the specified word with the replacement word in the input string.
#this method returns a new string with the specified replacement.
modified_string = input.replace(word_to_replace, replacement_word)

#Print the modified string with the word replaced.
print("Modified string:", modified_string)

Modified string: Python is a great programming language.


11. Count the occurrences of a word in a string.

In [ ]:
# Take the input from the user, the word whose occurrence we want to count.
input = "Python is a versatile programming language. Python is also known for its readability."
word_to_count = "Python"

#Using the split method to split the input into a list of words.This step seperates the string into individual words based on spaces.
words_list = input.split()

#Initialze a counter variable to keep track of the occurrences of the specified word.
word_count = 0

#Iterate through the words in the list and increment the counter each time the specified word is found.
for word in words_list:
    if word == word_to_count:
        word_count += 1

#print the total count of occurrences.
print(f"The word '{word_to_count}' occurs {word_count} times in the string.")


The word 'Python' occurs 2 times in the string.


12. Find the first occurrence of a word in a string.

In [ ]:
#Taking input from user.
input = "Python is a versatile programming language. python is also known for its readability."

#Word to find the first occurence
word_to_find = "python"

#Split the string into a list of words
words_list = input.split()

#Find the first occurrence
first_occurrence_index = -1 #Defaulf value if the word is not found.

for i,word in enumerate(words_list):
    if word == word_to_find:
        first_occurrence_index = i
        break

#Display the result.
if first_occurrence_index != -1:
    print(f"The first occurrence of '{word_to_find}' is at index {first_occurrence_index}.")
else:
    print(f"The word '{word_to_find}' is not found in the string.")

The first occurrence of 'python' is at index 6.


12. Find the first occurrence of a word in a string.

In [ ]:
#input from user
input =  "Python is a versatile programming language. python is also known for its readability."

#Word to find the first occurence
word_to_find = "python"

#Split the string into a list of words
words_list = input.split()

#Find the last occurrence
last_occurrence_index = -1 #Default value if the word is not found.

for i,word in enumerate(words_list):
    if word == word_to_find:
        last_occurrence_index = i

#Display the result
if last_occurrence_index != -1:
    print(f"The last occurrence of '{word_to_find}' is at index {last_occurrence_index}.")
else:
    print(f"The word '{word_to_find}' is not found in the string.")

The last occurrence of 'python' is at index 6.


13. Find the last occurrence of a word in a string.

In [ ]:
# Taking input from the users
input =  "Python is a versatile programming language. python is also known for its readability."

# Word to find the last  occurrence
word_to_find = "Python"

# Spliting the string into a list of words
words_list = input.split()

#Find the last occurrence
last_occurrence_index = -1 #Default value if the word is not found

for i in range(len(words_list) -1, -1, -1):
    if words_list[i] == word_to_find:
        last_occurrence_index = i
        break

#Print the index of the last occurrence or a message if the word is not found.
if last_occurrence_index != -1:
    print(f"The last occurrence of '{word_to_find}' is at index {last_occurrence_index}.")
else:
    print(f"The word '{word_to_find}' is not found in the string.")


The last occurrence of 'Python' is at index 0.


14. Split a string into a list of words.

In [ ]:
#Take the input that we want to split into words.
input = "Python is a versatile programming language."

# Apply the split method to the input. By default, this method splits the string into a list of words based om whitespace.

words_list = input.split()


#Print both the original string and the list of words.
print("Original_string:" , input)
print("List of words:" , words_list)



Original_string: Python is a versatile programming language.
List of words: ['Python', 'is', 'a', 'versatile', 'programming', 'language.']


15. Join a list of words into a string.

In [ ]:
# Creating a list of words that you want to join into a string
words_list = ['Python' , 'is' , 'a' , 'versatile' , 'programming' , 'language.']

#Using the join method on a string to concatenate the list of words.
joined_string = ' '.join(words_list) # In this example, a space(' ') is used as the separator between the words. We can use any string as a separator.

# Print both the original list of words and the joined string.
print("Original list of words:" , words_list)
print("Joined string:", joined_string)

Original list of words: ['Python', 'is', 'a', 'versatile', 'programming', 'language.']
Joined string: Python is a versatile programming language.


16. Convert a string where words are separated by spaces to one where words
are separated by underscores.

In [ ]:
# Taking the input string where words are separated by spaces.
input_string = "Python is a versatile programming language."

#Using the replace method to replace spaces with underscores in the input string.
converted_string = input_string.replace(' ','_')

#Print both the original string and the converted string.
print("Original string:" , input_string)
print("Converted string:", converted_string)

Original string: Python is a versatile programming language.
Converted string: Python_is_a_versatile_programming_language.


17. Check if a string starts with a specific word or phrase.

In [ ]:
# Take the input string and the specific word or phrase to check from the user.
input_string = "Python is known for its readability."
specific_word = "Python"

#Use the startswith method to check if the input string starts with the specified word or phrase.
starts_with_specific_word =  input_string.startswith(specific_word) # The startswith method returns True if the string starts with the specified prefix, otherwise, it returns Fales.

# Print whether the string starts with the specified word or phrase.
if starts_with_specific_word:
    print(f"The string starts with '{specific_word}'.")
else:
    print(f"The string does not start with '{specific_word}'.")


The string starts with 'Python'.


18. Check if a string ends with a specific word or phrase.

In [ ]:
# Take the input string and the specific word or phrase to check from the user
input_string = "Python is known for its readability."
specific_word = "readability"

# Use the endswith method to check if the input string ends with the specified word or phrase.
ends_with_specific_word = input_string.endswith(specific_word)
# The endseith method returns True if the string ends with the specified suffix;otherwise,it returns False.

# Print whether the string ends with the specified word or phrase.
if ends_with_specific_word:
    print(f"The string ends with '{specific_word}'.")
else:
    print(f"The string does not end with '{specific_word}'.")

The string does not end with 'readability'.


19. Convert a string to title case (e.g., "hello world" to "Hello World").

In [ ]:
# Take the input string that we want to convert to title case.
input_string = "hello world"

# Apply the title method to the input string. This method capitalizes the first letter of each word in the string.
title_case_string = input_string.title()

#Print both the original string and the string converted to title case.
print("Original string: ", input_string)
print("Title case string: ", title_case_string)

Original string:  hello world
Title case string:  Hello World


20. Find the longest word in a string.

In [ ]:
#Take the input string from the user
input_string = "Python is a versatile programming language, and programming is fun!"

# Use the split method to split the input string into a list of words.
words_list = input_string.split()

#Initialize variables to keep track of the longest word and its length
longest_word = ""
max_length = 0

#Iterate through the words in the list and update the variables if a longer word is found.
for word in words_list:
    if len(word) > max_length:
        longest_word = word
        max_length = len(word)

# Print the longest word and its length
print("Longest word:", longest_word)
print("Length of the longest word:", max_length)

Longest word: programming
Length of the longest word: 11


21. Find the shortest word in a string.

In [ ]:
# Take the input string from the user
input_string = "Python is a versatile programming language, and programming is fun!"

#Split the string into a list of words
words_list = input_string.split()

#Initialize variables
shortest_word = None
min_length = float('inf') #Initialize with positive infinity

# Find the shortest word
for word in words_list:
    if len(word) < min_length:
        shortest_word = word
        min_length = len(word)

#Display the result
print("Shortest word: ", shortest_word)
print("Length of the shortest word: ", min_length)

Shortest word:  a
Length of the shortest word:  1


22. Reverse the order of words in a string.

In [ ]:
input_string = "Python is a versatile programming language."
words_list = input_string.split()
reversed_words_list = words_list[::-1]
reversed_string = ' '.join(reversed_words_list)
print("Reversed string:", reversed_string)

23. Check if a string is alphanumeric.


In [ ]:
# Function to check if a string is alphanumeric
def is_alphanumeric(input_string):

        # Check if the string is alphanumeric using the isalnum() method
        return input_string.isalnum()

# Example usage
test_string = "Hello123"
result = is_alphanumeric(test_string)

# Display the result
if result:
    print(f"The string '{test_string}' is alphanumeric.")
else:
    print(f"The string '{test_string}' is not alphanumeric.")

The string 'Hello123' is alphanumeric.


24. Extract all digits from a string.


In [ ]:
# Function to extract all digits from a string
def extract_digits(input_string):

     # Use a list comprehension to extract digits from the string
        digits = [char for char in input_string if char.isdigit()]

          # Join the extracted digits into a string
        result_digit = ' '.join(digits)

# Example usage
input_str = "Hello123!"
result = extract_digits(input_str)

# Display the result
print(f"The extracted digits from the string are: {result}")


The extracted digits from the string are: None


We define a function extract_digits that takes a string (input_string) as its parameter.
List Comprehension to Extract Digits:

We use a list comprehension to iterate through each character in the input string (input_string).
The condition char.isdigit() checks if the character is a digit (0-9).
The result is a list (digits) containing only the numeric characters from the string.


We use the join() method to concatenate the extracted digits into a single string.


The function returns the final string containing only the extracted digits.


We provide an example string ("Hello123! This is an example with 456 digits.") and call the extract_digits function with this string.


Finally, we print the result, which is the string containing only the extracted digits.


25. Extract all alphabets from a string.


In [ ]:
# Function to extract all alphabets from a string
def extract_alphabets(input_string):
    # Use a list comprehension to extract alphabets from the string
    alphabets = [char for char in input_string if char.isalpha()]

    # Join the extracted alphabets into a string
    result_alphabets = ''.join(alphabets)

    # Return the final string containing only alphabets
    return result_alphabets

# Example usage
input_str = "Hello123!"
result = extract_alphabets(input_str)

# Display the result
print(f"The extracted alphabets from the string are: {result}")

The extracted alphabets from the string are: Hello




We define a function extract_alphabets that takes a string (input_string) as its parameter.
List Comprehension to Extract Alphabets:

We use a list comprehension to iterate through each character in the input string (input_string).
The condition char.isalpha() checks if the character is an alphabet (A-Z or a-z).
The result is a list (alphabets) containing only the alphabetic characters from the string.


We use the join() method to concatenate the extracted alphabets into a single string.


The function returns the final string containing only the extracted alphabets.


We provide an example string ("Hello123! This is an example with 456 digits.") and call the extract_alphabets function with this string.


Finally, we print the result, which is the string containing only the extracted alphabets.

26. Count the number of uppercase letters in a string.

In [ ]:
# Function to count uppercase letters in a string
def count_uppercase_letters(input_string):
    # Initialize a counter variable to keep track of uppercase letters
    uppercase_count = 0

    # Iterate through each character in the string
    for char in input_string:
        # Check if the character is an uppercase letter
        if char.isupper():
            # Increment the counter if it's an uppercase letter
            uppercase_count += 1

    # Return the final count
    return uppercase_count

# Example usage
input_str = "Gayatri Kale"
result = count_uppercase_letters(input_str)

# Display the result
print(f"The number of uppercase letters in the string is: {result}")

The number of uppercase letters in the string is: 2


We define a function count_uppercase_letters that takes a string (input_string) as its parameter.


We initialize a variable uppercase_count to 0. This variable will be used to keep track of the number of uppercase letters in the string.


We use a for loop to iterate through each character in the input string (input_string).


Inside the loop, we use the isupper() method to check if the current character is an uppercase letter.
If the condition is true, we increment the uppercase_count by 1.


After iterating through all the characters in the string, we return the final count of uppercase letters.


We provide an example string ("Hello World! This is an Example String.") and call the count_uppercase_letters function with this string.


Finally, we print the result, indicating the number of uppercase letters in the given string.

27. Count the number of lowercase letters in a string.


In [ ]:
# Function to count lowercase letters in a string
def count_lowercase_letters(input_string):
    # Initialize a counter variable to keep track of lowercase letters
    lowercase_count = 0

    # Iterate through each character in the string
    for char in input_string:
        # Check if the character is a lowercase letter
        if char.islower():
            # Increment the counter if it's a lowercase letter
            lowercase_count += 1

    # Return the final count
    return lowercase_count

# Example usage
input_str = "Gayatri Kale."
result = count_lowercase_letters(input_str)

# Display the result
print(f"The number of lowercase letters in the string is: {result}")

The number of lowercase letters in the string is: 9


We define a function count_lowercase_letters that takes a string (input_string) as its parameter.


We initialize a variable lowercase_count to 0. This variable will be used to keep track of the number of lowercase letters in the string.


We use a for loop to iterate through each character in the input string (input_string).


Inside the loop, we use the islower() method to check if the current character is a lowercase letter.
If the condition is true, we increment the lowercase_count by 1.

After iterating through all the characters in the string, we return the final count of lowercase letters.


We provide a new example string ("OpenAI's GPT-3 is an Advanced Language Model.") and call the count_lowercase_letters function with this string.


Finally, we print the result, indicating the number of lowercase letters in the given string.


28. Swap the case of each character in a string.


In [ ]:
# Function to swap the case of each character in a string
def swap_case(input_string):
    # Initialize an empty string to store the result
    swapped_string = ""

    # Iterate through each character in the input string
    for char in input_string:
        # Check if the character is an uppercase letter
        if char.isupper():
            # Convert uppercase to lowercase and append to the result string
            swapped_string += char.lower()
        # Check if the character is a lowercase letter
        elif char.islower():
            # Convert lowercase to uppercase and append to the result string
            swapped_string += char.upper()
        else:
            # If the character is not a letter, keep it unchanged
            swapped_string += char

    # Return the final swapped string
    return swapped_string

# Example usage
input_str = "Hello World! This is an Example String."
result = swap_case(input_str)

# Display the result
print(f"The string with swapped case is: {result}")


The string with swapped case is: hELLO wORLD! tHIS IS AN eXAMPLE sTRING.


We define a function swap_case that takes a string (input_string) as its parameter.
Initialize Result String:

We initialize an empty string swapped_string to store the result after swapping the case.
Iterate Through Characters:

We use a for loop to iterate through each character in the input string (input_string).
Swap Uppercase and Lowercase:

Inside the loop, we use the isupper() and islower() methods to check if the current character is uppercase or lowercase, respectively.
If the character is uppercase, we convert it to lowercase and append it to the swapped_string.
If the character is lowercase, we convert it to uppercase and append it to the swapped_string.
If the character is neither uppercase nor lowercase (e.g., punctuation or space), we keep it unchanged.
Return Final Swapped String:

After iterating through all the characters in the string, we return the final swapped_string.
Example Usage:

We provide an example string ("Hello World! This is an Example String.") and call the swap_case function with this string.
Display Result:

Finally, we print the result, which is the input string with the case of each character swapped.

29. Remove a specific word from a string.

In [ ]:
# Function to remove a specific word from a string
def remove_word(input_string, word_to_remove):
    # Split the input string into a list of words
    words = input_string.split()

    # Remove the specific word from the list
    words = [word for word in words if word.lower() != word_to_remove.lower()]

    # Join the remaining words back into a string
    result_string = ' '.join(words)

    # Return the final string without the specific word
    return result_string

# Example usage
input_str = "This is an example sentence. Remove this word from the sentence."
word_to_remove = "example"
result = remove_word(input_str, word_to_remove)

# Display the result
print(f"The string after removing the word is: {result}")


The string after removing the word is: This is an sentence. Remove this word from the sentence.


30. Check if a string is a valid email address.

In [ ]:
import re

# Function to check if a string is a valid email address
def is_valid_email(email):
    # Define a regular expression pattern for a valid email address
    email_pattern = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')

    # Use the re.match() function to check if the email matches the pattern
    match = email_pattern.match(email)

    # Return True if there is a match (valid email), otherwise return False
    return bool(match)

# Example usage
email_address = "user@example.com"
result = is_valid_email(email_address)

# Display the result
if result:
    print(f"The email address '{email_address}' is valid.")
else:
    print(f"The email address '{email_address}' is not valid.")

The email address 'user@example.com' is valid.


31. Extract the username from an email address string.

In [ ]:
# Function to extract the username from an email address
def extract_username(email):

       # Use the split() method to separate the username and domain
        username = email.split('@')[0]

          # Return the extracted username
        return username

# Example usage
email_address = "user@example.com"
result = extract_username(email_address)

# Print the result
print(f"The username from an email address is: {result}")

The username from an email address is: user


We define a function extract_username that takes an email address (email) as its parameter.

We use the split('@') method to split the email address into a list containing two parts: the username and the domain.
The [0] index is used to access the first part, which is the username.


The function returns the extracted username.


We provide an example email address ("user@example.com") and call the extract_username function with this address.


Finally, we print the result, which is the username extracted from the email address.

32. Extract the domain name from an email address string.

In [ ]:
# Function to extract the domain name from an email address
def extract_domain(email):

     # Use the split() method to separate the username and domain
        domain = email.split('@')[1]

    # Return the extracted domain
        return domain

#Example usage
email_address = "user@example.com"
result = extract_domain(email_address)

#Print the result
print(f"The domain from an email address is:{result}")



The domain from an email address is:example.com


We define a function extract_domain that takes an email address (email) as its parameter.


We use the split('@') method to split the email address into a list containing two parts: the username and the domain.
The [1] index is used to access the second part, which is the domain.


The function returns the extracted domain.


We provide an example email address ("user@example.com") and call the extract_domain function with this address.


Finally, we print the result, which is the domain extracted from the email address.

33. Replace multiple spaces in a string with a single space.

In [ ]:
# Function to replace multiple spaces with a single space in a string
def replace_multiple_spaces(input_string):

        # Use the split() method to break the string into words
        words = input_string.split()

        # Use the join() method to concatenate the words with a single space
        result_string = ' '.join(words)


    # Return the final string with single spaces
        return result_string

# Example usage
input_str = "This    is   an   example   with   multiple   spaces."
result = replace_multiple_spaces(input_str)


# Display the result
print(f"The string with multiple spaces replaced is:{result}")

The string with multiple spaces replaced is:This is an example with multiple spaces.


We define a function replace_multiple_spaces that takes a string (input_string) as its parameter.


We use the split() method without any arguments to break the input string into a list of words.
This method automatically handles consecutive spaces and treats them as a single delimiter.


We use the join() method to concatenate the words back into a string, separating them with a single space.
This effectively replaces multiple spaces with a single space.


The function returns the final string with single spaces.


We provide an example string ("This is an example with multiple spaces.") and call the replace_multiple_spaces function with this string.


Finally, we print the result, which is the original string with multiple spaces replaced by a single space.

34. Check if a string is a valid URL.

In [ ]:
import re

# Function to check if a string is a valid URL
def is_valid_url(url):
    # Define a regular expression pattern for a valid URL
    url_pattern = re.compile(
        r'^(https?|ftp):\/\/'  # Protocol (http, https, ftp)
        r'(?:(?:[a-zA-Z0-9$\-_.+!*\'(),;:@&=]|\%[0-9a-fA-F]{2})+@)?'  # Optional username and password
        r'(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}|'  # Domain name
        r'localhost|'  # localhost
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'  # Or an IP address
        r'(?::\d+)?'  # Optional port number
        r'(?:\/(?:[a-zA-Z0-9$\-_.+!*\'(),;:@&=]|(\%[0-9a-fA-F]{2}))+)*\/?'  # Path
        r'(?:\?(?:[a-zA-Z0-9$\-_.+!*\'(),;:@&=]|(\%[0-9a-fA-F]{2}))+)?'  # Query string
        r'(?:#(?:[a-zA-Z0-9$\-_.+!*\'(),;:@&=]|(\%[0-9a-fA-F]{2})))?$'  # Fragment identifier
    )

    # Use the re.match() function to check if the URL matches the pattern
    match = url_pattern.match(url)

    # Return True if there is a match (valid URL), otherwise return False
    return bool(match)

# Example usage
url = "https://www.example.com/path/to/page?param=value"
result = is_valid_url(url)

# Display the result
if result:
    print(f"The URL '{url}' is valid.")
else:
    print(f"The URL '{url}' is not valid.")


The URL 'https://www.example.com/path/to/page?param=value' is valid.


We import the re module, which provides support for regular expressions.


We define a regular expression pattern (url_pattern) that checks for a valid URL.
The pattern covers various components of a URL, including the protocol, optional username and password, domain name, IP address, port number, path, query string, and fragment identifier.


We use the re.match() function to check if the URL matches the defined pattern.
The match variable will be a match object if the URL is valid or None if it's not.


We return True if there is a match (indicating a valid URL), otherwise, we return False.


We provide an example URL ("https://www.example.com/path/to/page?param=value") and call the is_valid_url function with this URL.


Finally, we print whether the provided URL is valid or not.

35. Extract the protocol (http or https) from a URL string.

In [ ]:
import re

# Function to extract the protocol from a URL
def extract_protocol(url):
    # Define a regular expression pattern for extracting the protocol
    protocol_pattern = re.compile(r'^(https?|ftp)://')

    # Use the re.match() function to find the protocol in the URL
    match = protocol_pattern.match(url)

    # Return the extracted protocol or None if not found
    return match.group(1) if match else None

# Example usage
url = "https://www.example.com/path/to/page?param=value"
result = extract_protocol(url)

# Display the result
if result:
    print(f"The protocol extracted from the URL is: {result}")
else:
    print("No protocol found in the URL.")


The protocol extracted from the URL is: https


We import the re module, which provides support for regular expressions.


We define a regular expression pattern (protocol_pattern) that looks for the protocol part in a URL.
The pattern (https?|ftp) matches either "http," "https," or "ftp."


We use the re.match() function to check if the URL matches the defined pattern.
The match variable will be a match object if the protocol is found or None if it's not.


If a match is found, we use match.group(1) to retrieve the matched protocol.
If no match is found, we return None.


We provide an example URL ("https://www.example.com/path/to/page?param=value") and call the extract_protocol function with this URL.


Finally, we print the result, which is the protocol extracted from the URL.

36. Find the frequency of each character in a string.

In [ ]:
# Function to find the frequency of each character in a string
def character_frequency(input_string):
    # Create an empty dictionary to store character frequencies
    frequency_dict = {}

    # Iterate through each character in the string
    for char in input_string:
        # Increment the count for the current character in the dictionary
        frequency_dict[char] = frequency_dict.get(char, 0) + 1

    # Return the dictionary containing character frequencies
    return frequency_dict

# Example usage
input_str = "Hello, World!"
result = character_frequency(input_str)

# Display the result
print("Character frequencies in the string:")
for char, frequency in result.items():
    print(f"{char}: {frequency}")


Character frequencies in the string:
H: 1
e: 1
l: 3
o: 2
,: 1
 : 1
W: 1
r: 1
d: 1
!: 1


We define a function character_frequency that takes a string (input_string) as its parameter.


We create an empty dictionary (frequency_dict) to store the frequencies of each character.


We use a for loop to iterate through each character in the input string (input_string).


Inside the loop, we use the get() method to retrieve the current count of the character from the dictionary.
We increment the count by 1 and update the dictionary with the new count.


The function returns the dictionary containing the frequencies of each character.


We provide an example string ("Hello, World!") and call the character_frequency function with this string.


Finally, we print the result, which is the frequencies of each character in the string.

37. Remove all punctuation from a string.

In [ ]:
import string

# Function to remove all punctuation from a string
def remove_punctuation(input_string):
    # Use string.punctuation to get a string containing all punctuation characters
    punctuation_chars = string.punctuation

    # Use str.translate() to remove punctuation from the string
    translation_table = str.maketrans("", "", punctuation_chars)
    result_string = input_string.translate(translation_table)

    # Return the string without punctuation
    return result_string

# Example usage
input_str = "Hello, World! This is an example with punctuation."
result = remove_punctuation(input_str)

# Display the result
print(f"The string without punctuation is:\n{result}")


The string without punctuation is:
Hello World This is an example with punctuation


We import the string module, which provides a string containing all ASCII punctuation characters.


We use string.punctuation to get a string containing all punctuation characters.


We use str.maketrans("", "", punctuation_chars) to create a translation table.
We use str.translate() to remove characters listed in the translation table from the input string.


The function returns the string without punctuation.


We provide an example string ("Hello, World! This is an example with punctuation.") and call the remove_punctuation function with this string.


Finally, we print the result, which is the original string with punctuation removed.

38. Check if a string contains only digits.

In [ ]:
# Function to check if a string contains only digits
def contains_only_digits(input_string):
    # Use the isdigit() method to check if each character is a digit
    return all(char.isdigit() for char in input_string)

# Example usage
test_string = "12345"
result = contains_only_digits(test_string)

# Display the result
if result:
    print(f"The string '{test_string}' contains only digits.")
else:
    print(f"The string '{test_string}' does not contain only digits.")


The string '12345' contains only digits.


We define a function contains_only_digits that takes a string (input_string) as its parameter.


We use the isdigit() method, which is a built-in string method in Python.
This method returns True if all characters in the string are digits (0-9), and False otherwise.


The function returns the result obtained from applying the isdigit() method to each character in the string using a generator expression and the all() function.


We provide an example string ("12345") and call the contains_only_digits function with this string.


Finally, we print whether the provided string contains only digits or not.

39. Check if a string contains only alphabets.

In [ ]:
# Function to check if a string contains only alphabets
def contains_only_alphabets(input_string):
    # Use the isalpha() method to check if each character is an alphabet
    return all(char.isalpha() for char in input_string)

# Example usage
test_string = "Hello"
result = contains_only_alphabets(test_string)

# Display the result
if result:
    print(f"The string '{test_string}' contains only alphabets.")
else:
    print(f"The string '{test_string}' does not contain only alphabets.")


The string 'Hello' contains only alphabets.


We define a function contains_only_alphabets that takes a string (input_string) as its parameter.


We use the isalpha() method, which is a built-in string method in Python.
This method returns True if all characters in the string are alphabets (A-Z or a-z), and False otherwise.


The function returns the result obtained from applying the isalpha() method to each character in the string using a generator expression and the all() function.


We provide an example string ("Hello") and call the contains_only_alphabets function with this string.


Finally, we print whether the provided string contains only alphabets or not.

40. Convert a string to a list of characters.

In [ ]:
# Function to convert a string to a list of characters
def string_to_list(input_string):
    # Use list() to convert the string to a list of characters
    characters_list = list(input_string)

    # Return the list of characters
    return characters_list

# Example usage
input_str = "Hello"
result = string_to_list(input_str)

# Display the result
print(f"The string converted to a list of characters is: {result}")


The string converted to a list of characters is: ['H', 'e', 'l', 'l', 'o']


We define a function string_to_list that takes a string (input_string) as its parameter.


We use the list() function to convert the input string to a list of characters.
The list() function treats the input string as an iterable and creates a list where each character becomes an element.


The function returns the list of characters.


We provide an example string ("Hello") and call the string_to_list function with this string.


Finally, we print the result, which is the original string converted to a list of characters.

41. Check if two strings are anagrams.

In [ ]:
# Function to check if two strings are anagrams
def are_anagrams(str1, str2):
    # Remove spaces and convert to lowercase for case-insensitive comparison
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()

    # Check if the sorted characters of both strings are the same
    return sorted(str1) == sorted(str2)

# Example usage
string1 = "Listen"
string2 = "Silent"
result = are_anagrams(string1, string2)

# Display the result
if result:
    print(f"The strings '{string1}' and '{string2}' are anagrams.")
else:
    print(f"The strings '{string1}' and '{string2}' are not anagrams.")


The strings 'Listen' and 'Silent' are anagrams.


We define a function are_anagrams that takes two strings (str1 and str2) as its parameters.


We remove spaces from both strings and convert them to lowercase to perform a case-insensitive comparison.


We use the sorted() function to obtain sorted lists of characters for both strings.
We check if the sorted lists of characters for both strings are equal.


The function returns True if the strings are anagrams and False otherwise.


We provide two example strings ("Listen" and "Silent") and call the are_anagrams function with these strings.


Finally, we print whether the provided strings are anagrams or not.

42. Encode a string using a Caesar cipher.

In [ ]:
# Function to encode a string using a Caesar cipher
def caesar_cipher_encode(input_string, shift):
    # Initialize an empty string to store the encoded result
    encoded_string = ""

    # Iterate through each character in the input string
    for char in input_string:
        # Check if the character is an alphabet letter
        if char.isalpha():
            # Determine the case (uppercase or lowercase) of the character
            is_uppercase = char.isupper()

            # Shift the character by the specified amount
            shifted_char = chr((ord(char) - ord('A' if is_uppercase else 'a') + shift) % 26 + ord('A' if is_uppercase else 'a'))

            # Append the shifted character to the result string
            encoded_string += shifted_char
        else:
            # Keep non-alphabetic characters unchanged
            encoded_string += char

    # Return the encoded result string
    return encoded_string

# Example usage
input_str = "Hello, World!"
shift_amount = 3
result = caesar_cipher_encode(input_str, shift_amount)

# Display the result
print(f"The encoded string using a Caesar cipher is: {result}")


The encoded string using a Caesar cipher is: Khoor, Zruog!


We define a function caesar_cipher_encode that takes a string (input_string) and a shift amount (shift) as its parameters.


We initialize an empty string (encoded_string) to store the encoded result.


We use a for loop to iterate through each character in the input string (input_string).


We use the isalpha() method to check if the character is an alphabet letter.


We use the isupper() method to determine whether the character is uppercase or lowercase.


We calculate the shifted character using the formula (ord(char) - ord('A' if is_uppercase else 'a') + shift) % 26 + ord('A' if is_uppercase else 'a').
This formula ensures that the character is shifted by the specified amount while handling wrapping around the alphabet.


We append the shifted character to the result string.


If the character is not an alphabet letter, we keep it unchanged.


The function returns the encoded result string.


We provide an example string ("Hello, World!") and a shift amount (3) and call the caesar_cipher_encode function with these parameters.


Finally, we print the result, which is the original string encoded using a Caesar cipher.

43. Decode a Caesar cipher encoded string.

In [ ]:
# Function to encode a string using a Caesar cipher
def caesar_cipher_encode(input_string, shift):
    # Initialize an empty string to store the encoded result
    encoded_string = ""

    # Iterate through each character in the input string
    for char in input_string:
        # Check if the character is an alphabet letter
        if char.isalpha():
            # Determine the case (uppercase or lowercase) of the character
            is_uppercase = char.isupper()

            # Shift the character by the specified amount
            shifted_char = chr((ord(char) - ord('A' if is_uppercase else 'a') + shift) % 26 + ord('A' if is_uppercase else 'a'))

            # Append the shifted character to the result string
            encoded_string += shifted_char
        else:
            # Keep non-alphabetic characters unchanged
            encoded_string += char

    # Return the encoded result string
    return encoded_string

# Example usage
input_str = "Hello, World!"
shift_amount = 3
result = caesar_cipher_encode(input_str, shift_amount)

# Display the result
print(f"The encoded string using a Caesar cipher is: {result}")


The encoded string using a Caesar cipher is: Khoor, Zruog!


We define a function caesar_cipher_encode that takes a string (input_string) and a shift amount (shift) as its parameters.


We initialize an empty string (encoded_string) to store the encoded result.
Iterate Through Characters

We use a for loop to iterate through each character in the input string (input_string).


We use the isalpha() method to check if the character is an alphabet letter.


We use the isupper() method to determine whether the character is uppercase or lowercase.


We calculate the shifted character using the formula (ord(char) - ord('A' if is_uppercase else 'a') + shift) % 26 + ord('A' if is_uppercase else 'a').
This formula ensures that the character is shifted by the specified amount while handling wrapping around the alphabet.


We append the shifted character to the result string.


If the character is not an alphabet letter, we keep it unchanged.


The function returns the encoded result string.


We provide an example string ("Hello, World!") and a shift amount (3) and call the caesar_cipher_encode function with these parameters.


Finally, we print the result, which is the original string encoded using a Caesar cipher.

44. Find the most frequent word in a string.

In [ ]:
# Function to find the most frequent word in a string
def most_frequent_word(input_string):
    # Remove punctuation and convert to lowercase for accurate counting
    input_string = input_string.lower()
    input_string = ''.join(char if char.isalnum() or char.isspace() else ' ' for char in input_string)

    # Split the string into a list of words
    words = input_string.split()

    # Create a dictionary to store word frequencies
    word_frequency = {}

    # Iterate through each word and update the frequency in the dictionary
    for word in words:
        word_frequency[word] = word_frequency.get(word, 0) + 1

    # Find the word with the highest frequency
    most_frequent_word = max(word_frequency, key=word_frequency.get)

    # Return the most frequent word and its frequency
    return most_frequent_word, word_frequency[most_frequent_word]

# Example usage
input_str = "This is an example. This example demonstrates finding the most frequent word in a string."
result_word, result_frequency = most_frequent_word(input_str)

# Display the result
print(f"The most frequent word is '{result_word}' with a frequency of {result_frequency}.")


The most frequent word is 'this' with a frequency of 2.


We define a function most_frequent_word that takes a string (input_string) as its parameter.


We remove punctuation from the string and convert it to lowercase to ensure accurate word counting.


We use the split() method to break the string into a list of words.


We create an empty dictionary (word_frequency) to store word frequencies.


We iterate through each word in the list and update its frequency in the dictionary using the get() method.


We use the max() function with the key argument set to word_frequency.get to find the word with the highest frequency.


The function returns the most frequent word and its frequency.


We provide an example string and call the most_frequent_word function with this string.


Finally, we print the result, which is the most frequent word and its frequency.

45. Find all unique words in a string.

In [ ]:
# Function to find all unique words in a string
def unique_words(input_string):
    # Remove punctuation and convert to lowercase for accurate counting
    input_string = input_string.lower()
    input_string = ''.join(char if char.isalnum() or char.isspace() else ' ' for char in input_string)

    # Split the string into a list of words
    words = input_string.split()

    # Create a set to store unique words
    unique_word_set = set(words)

    # Convert the set back to a sorted list for display
    unique_word_list = sorted(list(unique_word_set))

    # Return the list of unique words
    return unique_word_list

# Example usage
input_str = "This is an example. This example demonstrates finding unique words in a string."
result = unique_words(input_str)

# Display the result
print(f"The unique words in the string are: {result}")


The unique words in the string are: ['a', 'an', 'demonstrates', 'example', 'finding', 'in', 'is', 'string', 'this', 'unique', 'words']


We define a function unique_words that takes a string (input_string) as its parameter.


We remove punctuation from the string and convert it to lowercase to ensure accurate word identification.


We use the split() method to break the string into a list of words.


We create an empty set (unique_word_set) to store unique words.
Sets automatically eliminate duplicate entries.


We convert the set back to a sorted list (unique_word_list) for display purposes.


The function returns the list of unique words.


We provide an example string and call the unique_words function with this string.


Finally, we print the result, which is the list of unique words.

46. Count the number of syllables in a string.

In [ ]:
# Function to count the number of syllables in a word
def count_syllables_in_word(word):
    vowels = "aeiouy"
    count = 0
    is_vowel = False

    # Iterate through each character in the word
    for char in word.lower():
        # Check if the character is a vowel
        if char in vowels:
            # If the current character is a vowel and the previous character was not, increment the count
            if not is_vowel:
                count += 1
            is_vowel = True
        else:
            is_vowel = False

    # Adjust the count for special cases
    if count == 0:
        count = 1

    return count

# Function to count the number of syllables in a string
def count_syllables(input_string):
    # Remove punctuation and convert to lowercase for accurate counting
    input_string = input_string.lower()
    input_string = ''.join(char if char.isalnum() or char.isspace() else ' ' for char in input_string)

    # Split the string into a list of words
    words = input_string.split()

    # Count syllables for each word and sum the counts
    total_syllables = sum(count_syllables_in_word(word) for word in words)

    return total_syllables

# Example usage
input_str = "This is an example sentence demonstrating syllable counting."
result = count_syllables(input_str)

# Display the result
print(f"The number of syllables in the string is: {result}")


The number of syllables in the string is: 18


We define a function count_syllables_in_word that takes a word as its parameter.
This function counts the number of syllables in a single word.


We define a string of vowels (vowels) and initialize a counter (count) to 0.
We also initialize a flag (is_vowel) to keep track of whether the current character is a vowel.


We use a for loop to iterate through each character in the word.
We check if each character is a vowel and update the count accordingly.


If the count is 0, we adjust it to 1. This helps handle cases where a word has no vowels.


We define a function count_syllables that takes a string (input_string) as its parameter.
This function counts the number of syllables in the entire string.


We remove punctuation from the string and convert it to lowercase for accurate counting.


We use the split() method to break the string into a list of words.


We iterate through each word in the list and use the count_syllables_in_word function to count syllables in each word.
We sum the counts for all words to get the total number of syllables.


The function returns the total number of syllables in the string.


We provide an example string and call the count_syllables function with this string.


Finally, we print the result, which is the total number of syllables in the string.

47. Check if a string contains any special characters.

In [ ]:
# Function to check if a string contains any special characters
def contains_special_characters(input_string):
    # Iterate through each character in the string
    for char in input_string:
        # Check if the character is a special character
        if not char.isalnum():
            return True  # Return True if a special character is found

    # Return False if no special characters are found
    return False

# Example usage
test_string = "Hello123"
result = contains_special_characters(test_string)

# Display the result
if result:
    print(f"The string '{test_string}' contains special characters.")
else:
    print(f"The string '{test_string}' does not contain special characters.")


The string 'Hello123' does not contain special characters.


We define a function contains_special_characters that takes a string (input_string) as its parameter.


We use a for loop to iterate through each character in the input string (input_string).


We use the isalnum() method to check if the character is alphanumeric (i.e., a letter or a digit).
If the character is not alphanumeric, it is considered a special character.


The function returns True if any special characters are found, and False otherwise.


We provide an example string ("Hello123") and call the contains_special_characters function with this string.


Finally, we print whether the provided string contains any special characters or not.

48. Remove the nth word from a string.

In [ ]:
# Function to remove the nth word from a string
def remove_nth_word(input_string, n):
    # Split the string into words
    words = input_string.split()

    # Check if the index is valid
    if 1 <= n <= len(words):
        # Remove the nth word
        del words[n - 1]

        # Join the remaining words into a string
        result_string = ' '.join(words)

        return result_string
    else:
        # If the index is invalid, return the original string
        return input_string

# Example usage
input_str = "This is an example sentence."
index_to_remove = 3
result = remove_nth_word(input_str, index_to_remove)

# Display the result
print(f"The string after removing the {index_to_remove}th word is:\n{result}")


The string after removing the 3th word is:
This is example sentence.


We define a function remove_nth_word that takes a string (input_string) and an index (n) as its parameters.


We use the split() method to break the string into a list of words.


We check if the specified index is within the valid range (1 to the number of words in the string).


If the index is valid, we use del to remove the word at the specified index.


We use join() to concatenate the remaining words into a string.


The function returns the modified string if the index is valid, or the original string if the index is invalid.


We provide an example string ("This is an example sentence.") and an index to remove (3), then call the remove_nth_word function.

Finally, we print the result, which is the string after removing the nth word.

49. Insert a word at the nth position in a string.

In [ ]:
# Function to insert a word at the nth position in a string
def insert_word_at_nth_position(input_string, new_word, n):
    # Split the string into words
    words = input_string.split()

    # Check if the index is valid
    if 0 <= n <= len(words):
        # Insert the new word at the specified index
        words.insert(n, new_word)

        # Join the words into a string
        result_string = ' '.join(words)

        return result_string
    else:
        # If the index is invalid, return the original string
        return input_string

# Example usage
input_str = "This is an example sentence."
word_to_insert = "new"
index_to_insert = 2
result = insert_word_at_nth_position(input_str, word_to_insert, index_to_insert)

# Display the result
print(f"The string after inserting '{word_to_insert}' at position {index_to_insert} is:\n{result}")


The string after inserting 'new' at position 2 is:
This is new an example sentence.


We define a function insert_word_at_nth_position that takes a string (input_string), a new word (new_word), and an index (n) as its parameters.


We use the split() method to break the string into a list of words.


We check if the specified index is within the valid range (0 to the number of words in the string).


If the index is valid, we use insert() to add the new word at the specified index.


We use join() to concatenate the words into a string.


The function returns the modified string if the index is valid, or the original string if the index is invalid.


We provide an example string ("This is an example sentence."), a new word to insert ("new"), and an index to insert at (2), then call the insert_word_at_nth_position function.


Finally, we print the result, which is the string after inserting the new word at the specified position.

50. Convert a CSV string to a list of lists.

In [ ]:
import csv
from io import StringIO

# Function to convert a CSV string to a list of lists
def csv_string_to_list(csv_string):
    # Use StringIO to create a file-like object for the csv.reader
    csv_file = StringIO(csv_string)

    # Use csv.reader to read the CSV data
    csv_reader = csv.reader(csv_file)

    # Convert the csv_reader object to a list of lists
    csv_list = list(csv_reader)

    return csv_list

# Example usage
csv_string = "Name,Age,Location\nJohn,25,New York\nAlice,30,San Francisco\nBob,22,Los Angeles"
result = csv_string_to_list(csv_string)

# Display the result
print("The CSV string converted to a list of lists is:")
for row in result:
    print(row)


The CSV string converted to a list of lists is:
['Name', 'Age', 'Location']
['John', '25', 'New York']
['Alice', '30', 'San Francisco']
['Bob', '22', 'Los Angeles']


List Based Practice Problem :

1. Create a list with integers from 1 to 10.

In [ ]:
# Use the range() function to generate a sequence of numbers
number_range = range(1, 11) # Numbers from 1 to 10 (11 is not included)

# Convert the range object to a list
number_list = list(number_range)

# Display the result
print(f"The list of integers from 1 to 10:", number_list)

The list of integers from 1 to 10: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


We use the range(1, 11) function to generate a sequence of numbers starting from 1 up to (but not including) 11.

We use list(number_range) to convert the range object to a list.

Finally, we print the result, which is the list of integers from 1 to 10.

2. Find the length of a list without using the `len()` function.

In [ ]:
#Example list
example_list = [1,2,3,4,5,6,7,8,9,10]

# Initialize a counter variable
length_counter = 0

# Iterate through each element in the list
for i in example_list:

      # Increment the counter for each element
        length_counter += 1

# Display the result
print(f"The length of the list is: {length_counter}")

The length of the list is: 10


We start with an example list named example_list containing integers from 1 to 10.

We initialize a counter variable (length_counter) to 0. This variable will be used to count the elements in the list.

We use a for loop to iterate through each element in the list. The loop variable is denoted by _ (underscore) as we don't need its value.

For each element encountered in the list, we increment the counter (length_counter) by 1.

Finally, we print the result, which is the length of the list obtained by counting the elements.

3. Append an element to the end of a list.

In [ ]:
#Example list
original_list = [1,2,3,4,5]

#Element to append
new_element = 6

# Use the append() method to add the new element to the end of the list
original_list.append(new_element)

# Display the updated list
print(f"The list after appending the new element is:", original_list)

The list after appending the new element is: [1, 2, 3, 4, 5, 6]


We start with an example list named original_list containing integers from 1 to 5.

We have a new element (new_element) that we want to append to the end of the list. In this example, the new element is 6.

We use the append() method on the original_list to add the new element to the end of the list.
The append() method modifies the list in place.

We print the result, which is the list after appending the new element.

4. Insert an element at a specific index in a list.

In [ ]:
#Original list
original_list = [1,2,3,5,6]

#Element to insert
new_element = 4

#Index to insert the new element
insert_index = 3

# Use the insert() method to add the new element at the specified index
original_list.insert(insert_index, new_element)

# Display the updated list
print(f"The list after inserting the new element is:", original_list)

The list after inserting the new element is: [1, 2, 3, 4, 5, 6]


We start with an original list named original_list containing integers from 1 to 6.

We have a new element (new_element) that we want to insert into the list. In this example, the new element is 4.

We specify the index (insert_index) where we want to insert the new element. In this example, the index is 3.
U
We use the insert() method on the original_list to add the new element at the specified index.
The insert() method modifies the list in place.

We print the result, which is the list after inserting the new element.

5. Remove an element from a list by its value.

In [ ]:
#list
original_list = [1,2,3,4,5,6]

#Element to remove
element_to_remove = 4

# Use the remove() method to remove the specified element
original_list.remove(element_to_remove)

# Use the remove() method to remove the specified element
print(f"The list after removing the element is:", original_list)

The list after removing the element is: [1, 2, 3, 5, 6]


We start with an example list named original_list containing integers, including the value 3 that we want to remove.

We specify the element (element_to_remove) that we want to remove from the list. In this example, the element is 3.

We use the remove() method on the original_list to remove the specified element.
The remove() method modifies the list in place and removes the first occurrence of the specified value.

We print the result, which is the list after removing the specified element.

6. Remove an element from a list by its index.

In [ ]:
#Original list
original_list = [1,2,3,4,5,6,7]

# Index of the element to remove
index_to_remove = 2

# Use the pop() method to remove the element at the specified index
removed_element = original_list.pop(index_to_remove)

# Display the updated list and the removed element
print(f"The list after removing the element is:", original_list)
print(f"Removed element:", removed_element)

The list after removing the element is: [1, 2, 4, 5, 6, 7]
Removed element: 3


We start with an example list named original_list containing integers.

We specify the index (index_to_remove) of the element that we want to remove from the list. In this example, the index is 2.

We use the pop() method on the original_list with the specified index to remove the element.
The pop() method modifies the list in place and returns the removed element.

We print the result, which is the list after removing the specified element, and we also display the removed element.

7. Check if an element exists in a list.

In [ ]:
# Example list
example_list = [1, 2, 3, 4, 5]

# Element to check
element_to_check = 3

# Use the 'in' keyword to check if the element exists
element_exists = element_to_check in example_list

# Display the result
if element_exists:
    print(f"The element {element_to_check} exists in the list.")
else:
    print(f"The element {element_to_check} does not exist in the list.")


The element 3 exists in the list.


We start with an example list named example_list containing integers.

We specify the element (element_to_check) that we want to check for in the list. In this example, the element is 3.

We use the in keyword to check if the specified element exists in the list. The result is a boolean value (True or False).

We print the result, indicating whether the element exists in the list or not.
When you run each of the provided examples, you will get one of the following outputs:

If the element exists: "The element 3 exists in the list."
If the element does not exist: "The element 3 does not exist in the list."
You can modify the element_to_check variable to test different elements.








8. Find the index of the first occurrence of an element in a list.

In [ ]:
# Example list
example_list = [1, 2, 3, 4, 3, 5]

# Element to find the index of
element_to_find = 3

# Use the index() method to find the index of the first occurrence
try:
    index_of_element = example_list.index(element_to_find)
    print(f"The index of the first occurrence of {element_to_find} is: {index_of_element}")
except ValueError:
    print(f"The element {element_to_find} is not in the list.")


The index of the first occurrence of 3 is: 2


We start with an example list named example_list containing integers.

We specify the element (element_to_find) for which we want to find the index. In this example, the element is 3.

We use the index() method on the original_list to find the index of the first occurrence of the specified element.
If the element is not found, a ValueError is raised, so we use a try-except block to handle this case.

We print the result, which is the index of the first occurrence of the specified element, or a message indicating that the element is not in the list.

9. Count the occurrences of an element in a list.

In [ ]:
# Example list
example_list = [1, 2, 3, 4, 3, 5, 3]

# Element to count occurrences of
element_to_count = 3

# Use the count() method to count occurrences of the element
occurrences_count = example_list.count(element_to_count)

# Display the result
print(f"The element {element_to_count} appears {occurrences_count} times in the list.")


The element 3 appears 3 times in the list.


We start with an example list named example_list containing integers.

We specify the element (element_to_count) for which we want to count occurrences. In this example, the element is 3.

We use the count() method on the original_list to count the occurrences of the specified element.

We print the result, which is the count of occurrences of the specified element in the list.

10. Reverse the order of elements in a list.

In [ ]:
# Example list
example_list = [1, 2, 3, 4, 5]

# Use the reverse() method to reverse the order of elements in the list
example_list.reverse()

# Display the updated list
print("The list after reversing the order is:", example_list)


The list after reversing the order is: [5, 4, 3, 2, 1]


We start with an original list named original_list containing integers.

We use the reverse() method on the example_list to reverse the order of elements in place.

Alternatively, we use slicing ([::-1]) to create a new list with the elements in reversed order.

We print the result, which is the list after reversing the order or the new reversed list.
When you run each of the provided examples, you will get one of the following outputs:

Using reverse(): "The list after reversing the order is: [5, 4, 3, 2, 1]"
Using slicing: "The reversed list is: [5, 4, 3, 2, 1]"

Both approaches achieve the same result of reversing the order of elements in the list. You can choose the method that best fits your needs.

11. Sort a list in ascending order.

In [ ]:
#Original list
original_list = [5,3,4,6,2,1]

# Use sorting method to sort the list in ascending order
original_list.sort()

#Print the result
print(f"The list in ascending order is:", original_list)

The list in ascending order is: [1, 2, 3, 4, 5, 6]


We start with an original list named original_list containing integers.

We use the sort() method on the original_list to sort the elements in ascending order in place.
Using the sorted() Function:

We print the result, which is the list after sorting in ascending order or the new sorted list.
When you run each of the provided examples, you will get one of the following outputs:

Using sort(): "The list sorted in ascending order is: [1, 2, 3, 5, 8]"


12. Sort a list in descending order.

In [ ]:
#Original list
original_list = [6,3,4,5,2,1]

#Use sort() method with reverse = True to sort the list in descending order
original_list.sort(reverse = True)

#Print the result
print(f"The list in descending order is:",original_list)

The list in descending order is: [6, 5, 4, 3, 2, 1]


We start with an  list namedoriginal_list containing integers.

We use the sort() method on the example_list with the reverse=True argument to sort the elements in descending order in place.

We print the result, which is the list after sorting in descending order or the new sorted list in descending order.
When you run each of the provided examples, you will get one of the following outputs:

Using sort(): "The list sorted in descending order is: [8, 5, 3, 2, 1]"

13. Create a list of even numbers from 1 to 20.

In [ ]:
# Use the range() function to generate even numbers form 2 to 20
even_numbers = range(2, 21, 2)

# Convert the range object to a list using list comprehension
even_numbers_list = [num for num in even_numbers]

# Display the list of even numbers
print(f"The list of even numbers from 1 to 20 is:",even_numbers_list)


The list of even numbers from 1 to 20 is: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


We use the range(2, 21, 2) function to generate a sequence of even numbers starting from 2 up to (but not including) 21 with a step size of 2.

We use list comprehension to convert the range object to a list containing even numbers.

We print the result, which is the list of even numbers from 1 to 20.

14. Create a list of odd numbers from 1 to 20.

In [ ]:
# Use the range() function to generate odd numbers from 1 to 20
odd_numbers = range(1,21,2)

#Convert the range object to a list using list comprehension
odd_numbers_list = [num for num in odd_numbers]

#Diplsy the listg of even numbers
print(f"The list of odd numbers from 1 to 20 is:",odd_numbers_list)

The list of odd numbers from 1 to 20 is: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


We use the range(1, 21, 2) function to generate a sequence of odd numbers starting from 1 up to (but not including) 21 with a step size of 2.

We use list comprehension to convert the range object to a list containing odd numbers.

We print the result, which is the list of odd numbers from 1 to 20.

15. Find the sum of all elements in a list.

In [ ]:
#Original list
original_list = (4,5,6,8,9)

#Use the sum() function to find the sum of all elements in a list.
sum_of_elements = sum(original_list)

#Print the result
print(f"The sum of all elements in a list is:",sum_of_elements)

The sum of all elements in a list is: 32


We start with an original list named original_list containing integers.

We use the sum() function on the example_list to find the sum of all elements.

We print the result, which is the sum of all elements in the list.

16. Find the maximum value in a list.

In [ ]:
# Original list
original_list = [3, 7, 1, 9, 4, 5]

#Use the max() function to find the maximum value in a list.
max_value = max(original_list)

# Display the result
print(f"The maximum value in a list is:",max_value)

The maximum value in a list is: 9


We start with an original list named original_list containing integers.

We use the max() function on the example_list to find the maximum value.

We print the result, which is the maximum value in the list.

17. Find the minimum value in a list.

In [ ]:
#Original list
original_list = [3,7,1,9,4,5]

# Use the min() function to find the minimum value in a list.
min_value = min(original_list)

#Diplay the result
print(f"The minimum value in a list is:",min_value)

The minimum value in a list is: 1


We start with an original list named original_list containing integers.

We use the max() function on the original_list to find the maximum value.

We print the result, which is the maximum value in the list.

18. Create a list of squares of numbers from 1 to 10.

In [ ]:
# Step 1: Use list comprehension to create a list of squares
squares_list = [num**2 for num in range(1, 11)]

# Step 2: Display the list of squares
print("The list of squares from 1 to 10 is:", squares_list)


The list of squares from 1 to 10 is: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


We use list comprehension to create a list (squares_list) of squares for each number in the range from 1 to 10.

We print the result, which is the list of squares from 1 to 10.

19. Create a list of random numbers.

In [ ]:
import random

# Define the size of the list and the range of random numbers
list_size =5
min_value = 1
max_value = 100

# Use list comprehension to create a list of random numbers
random_list_numbers = [random.randint(min_value, max_value) for _ in range (list_size)]

# Display the list of random numbers
print(f"The list of random numbers is:",random_list_numbers)

The list of random numbers is: [14, 40, 82, 55, 33]


We import the random module to use its functions for generating random numbers.

We define the size of the list (list_size) and the range of random numbers (min_value to max_value).

We use list comprehension to create a list (random_numbers_list) of random numbers within the specified range.

We print the result, which is the list of random numbers.

20. Remove duplicates from a list.

In [ ]:
# Example list with duplicates
original_list = [1,2,2,3,4,4,5,6,6]

# Convert the list to a set to remove duplicates
unique_set = set(original_list)

#Convert the set back to a list
unique_list = list(unique_set)

#Print the list without duplicate
print(f"The list without duplicate is:",unique_list)

The list without duplicate is: [1, 2, 3, 4, 5, 6]


We start with an example list named original_list containing duplicate elements.

We convert the list to a set (unique_set) to automatically remove duplicates since sets only store unique elements.
We then convert the set back to a list (unique_list).

We print the result, which is the list without duplicates.

21. Find the common elements between two lists.

In [ ]:
#Example list
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Convert lists to sets and find the intersection
common_element_set = set(list1).intersection(list2)

# Convert the set back to a list
common_element_list = list(common_element_set)

#Print the result
print(f"The common elements between two lists is:",common_element_list)

The common elements between two lists is: [3, 4, 5]


We start with two example lists, list1 and list2, containing integers.
Using Set Intersection:

We convert both lists to sets and use the intersection method to find the common elements.
We then convert the resulting set back to a list.

We print the result, which is the list of common elements between the two lists.

22. Find the difference between two lists.

In [ ]:
# Example lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Step 1: Convert lists to sets and find the difference
difference_set = set(list1).difference(list2)

# Convert the set back to a list
difference_list = list(difference_set)

#Print the result
print(f"The difference between two lists is:", difference_list)

The difference between two lists is: [1, 2]


We start with two example lists, list1 and list2, containing integers.
Using Set Difference:

We convert both lists to sets and use the difference method to find the elements that are unique to list1.
We then convert the resulting set back to a list.

We print the result, which is the list of elements that are unique to list1.

23. Merge two lists.

In [ ]:
# Example lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Use the extend() method to merge the lists
list1.extend(list2)

#Display the merge list
print(f"The merge list is:", list1)

The merge list is: [1, 2, 3, 4, 5, 6]


We start with two example lists, list1 and list2, containing integers.

We use the extend() method on list1 to add the elements of list2 to it.

We print the result, which is the merged list.

24. Multiply all elements in a list by 2.

In [ ]:
#Example list
original_list = [1,2,3,4,5,6]

# Use list comprehension to multiply each element by 2
doubled_list = [item * 2 for item in original_list]

#Display the multiplied list
print(f"The multilpy all elements in a list by 2 is:",doubled_list)

The multilpy all elements in a list by 2 is: [2, 4, 6, 8, 10, 12]


We start with an example list named original_list containing integers.

We use list comprehension to iterate through original_list and multiply each element by 2, creating a new list (doubled_list).

We print the result, which is the list after multiplying each element by 2.

25. Filter out all even numbers from a list.

In [ ]:
#Original list
original_list = [1,2,3,4,5,6,7,8,9,10]

# Use list comprehension to filter out even numbers
filtered_list = [item for item in original_list if item % 2 != 0]

# Diplay the filtered list
print(f"The list after filtering out even numbers is:", filtered_list)

The list after filtering out even numbers is: [1, 3, 5, 7, 9]


We start with an example list named original_list containing integers.

We use list comprehension to iterate through original_list and include only the elements that are not even (filtered by the condition item % 2 != 0).

We print the result, which is the list after filtering out even numbers.

26. Convert a list of strings to a list of integers.

In [ ]:
# Example list of strings
string_list = ['1','2','3','4','5','6']

#Use list comprehension to convert strings to integers
integer_list = [int(item) for item in string_list]

#Display the list of integers
print(f"The list of integers is:", integer_list)

The list of integers is: [1, 2, 3, 4, 5, 6]


We start with an example list named string_list containing strings representing integers.
Using List Comprehension:

We use list comprehension to iterate through string_list and convert each string to an integer using the int() function.
Display the Result:

We print the result, which is the list of integers.

27. Convert a list of integers to a list of strings.

In [ ]:
#Example list of intergers
integer_list = [1,2,3,4,5,6]

#Use list comprehension to convert intergers to strings
string_list = [str(item) for item in integer_list]

#Display the list of string
print(f"The list of strings is:",string_list)

The list of strings is: ['1', '2', '3', '4', '5', '6']


We start with an example list named integer_list containing integers.

We use list comprehension to iterate through integer_list and convert each integer to a string using the str() function.

We print the result, which is the list of strings.

28. Flatten a nested list.

In [ ]:
#Example nested list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#Use nested list comprehension to flatten the list
flattended_list = [item for sublist in nested_list for item in sublist]

# Diplay the flattended list
print(f"The flattened list is:",flattended_list)

The flattened list is: [1, 2, 3, 4, 5, 6, 7, 8, 9]


We start with an example nested list named nested_list containing sublists.
Using Nested List Comprehension:

We use nested list comprehension to iterate through both the outer list and each sublist, effectively flattening the structure.
Display the Result:

We print the result, which is the flattened list.

29. Create a list of the first 10 Fibonacci numbers.

In [ ]:
# Step 1: Initialize variables for the first two Fibonacci numbers
fibonacci_numbers = [0, 1]

# Step 2: Use a loop to generate the next 8 Fibonacci numbers
for _ in range(8):
    next_number = fibonacci_numbers[-1] + fibonacci_numbers[-2]
    fibonacci_numbers.append(next_number)

# Step 3: Display the list of the first 10 Fibonacci numbers
print("The first 10 Fibonacci numbers are:", fibonacci_numbers)


The first 10 Fibonacci numbers are: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


We start with the first two Fibonacci numbers, which are 0 and 1.

We use a loop to generate the next 8 Fibonacci numbers. The loop calculates each Fibonacci number by adding the two preceding numbers and appends it to the list.

We print the result, which is the list of the first 10 Fibonacci numbers.

30. Check if a list is sorted.

In [ ]:
# Example list
sorted_list = [1, 2, 3, 4, 5]

# Step 1: Use a loop to check if the list is sorted
is_sorted = all(sorted_list[i] <= sorted_list[i + 1] for i in range(len(sorted_list) - 1))

# Step 2: Display the result
if is_sorted:
    print("The list is sorted.")
else:
    print("The list is not sorted.")



The list is sorted.


We start with an example list named sorted_list containing integers.

We use a loop to check if each element in the list is less than or equal to its successor. The all() function ensures that the condition holds for all pairs of adjacent elements.

We print the result, indicating whether the list is sorted or not.

31. Rotate a list to the left by `n` positions.

In [ ]:
#Original list
original_list = [1,2,3,4,5]

# Number of positions to rotate
n = 4

#Use slicing to rotate the list to the left by n positions
rotated_list = original_list [n:] + original_list [:n]

#Display the rotated list
print(f"The list after rotate to the left by n position:",rotated_list)

The list after rotate to the left by n position: [5, 1, 2, 3, 4]


We start with an original list named original_list containing integers.

We define the number of positions to rotate the list to the left (in this case, n = 4).

We use slicing to create a new list (rotated_list) by combining the sublist starting from position n to the end and the sublist from the beginning up to position n.

We print the result, which is the list after rotating it to the left by n positions.

32. Rotate a list to the right by `n` positions.

In [ ]:
# Original list
original_list = [1,2,3,4,5]

#Number of position to rotate
n = 4

#Use slicing to rotate the list to the right by n position
rotated_list = original_list[-n:] + original_list [:-n]

#Display the rotated list
print(f"The list after rotate to the right by n position:", rotated_list)

The list after rotate to the right by n position: [2, 3, 4, 5, 1]


33. Create a list of prime numbers up to 50.

In [ ]:
#Define a function to check for primality
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
        return True

#Use a loop to generate a list of prime numbers up to 50
prime_numbers = [num for num in range(2,51) if is_prime(num)]

#Display the list of prime numbers
print(f"The list of prime numbers up to 50 is:", prime_numbers)

The list of prime numbers up to 50 is: [5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


We define a function named is_prime to check if a given number is prime. This function uses a loop to check for divisibility by numbers up to the square root of the given number.

We use a list comprehension to generate a list (prime_numbers) of prime numbers by iterating through the numbers from 2 to 50 and selecting only the prime ones.

We print the result, which is the list of prime numbers up to 50.

34. Split a list into chunks of size `n`.

In [ ]:
# Example list
original_list = [1,2,3,4,5,6,7,8,9,10]

#Size of each chunk
n = 3

# Use a loop to split the list into chunks
chunked_list = [original_list [i:i + n] for i in range (0, len(original_list), n)]

# Display the list of chunks
print(f"The list into chunks of size n is:", chunked_list)



The list into chunks of size n is: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]


35. Find the second largest number in a list.

In [ ]:
# Example list
number_list = [10, 5, 8, 20, 15]

#Use list comprehension to find unique numbers in the list
unique_numbers = list(set(number_list))

#Use the max() function to find the second-largest number
second_largest = max(unique_numbers) if len(unique_numbers) < 2 else max(num for num in unique_numbers if num != max(unique_numbers))

# Display the second-largest number
print("The second-largest number is:", second_largest)

The second-largest number is: 15


We start with an example list named number_list containing integers.

We use list comprehension to create a list (unique_numbers) containing unique elements from the original list. We convert the list to a set to remove duplicates and then convert it back to a list.

We use the max() function to find the second-largest number. If there are fewer than two unique numbers, it means that the list has only one distinct element, so we use the maximum value as the second-largest. Otherwise, we find the maximum value excluding the largest value.

We print the result, which is the second-largest number.

36. Replace every element in a list with its square.

In [ ]:
# Example list
original_list = [45,56,78,98,12]

#Use list comprehension to square each element
squared_list = [item ** 2 for item in original_list]

#Display the list with squared elements
print(f"The list with squared list is:",squared_list)

The list with squared list is: [2025, 3136, 6084, 9604, 144]


We start with an example list named original_list containing integers.

We use list comprehension to iterate through original_list and replace each element with its square (item ** 2).

We print the result, which is the list with squared elements.

37. Convert a list to a dictionary where list elements become keys and their
indices become values.

In [ ]:
# Oiginal list
original_list = ['apple', 'banana', 'orange', 'grape']

#Use dictionary comprehension with enumerate()
result_dict = { value : index for index, value in enumerate(original_list)}

# Display the resulting dictionary
print("The dictionary with list elements as keys and indices as values is:", result_dict)

The dictionary with list elements as keys and indices as values is: {'apple': 0, 'banana': 1, 'orange': 2, 'grape': 3}


We start with an example list named original_list containing strings.

We use dictionary comprehension with enumerate(original_list) to iterate through the elements of the list along with their indices. Each element becomes a key, and its index becomes the corresponding value in the dictionary.

We print the result, which is the dictionary with list elements as keys and indices as values.

38. Shuffle the elements of a list randomly.

In [ ]:
import random

# Original list
original_list = [1,2,3,4,5]

#Use random.shuffle() to shuffle the list in-place
random.shuffle(original_list)

# Display the shuffled list
print(f" The list after shuffling is:", original_list)

 The list after shuffling is: [2, 1, 5, 4, 3]


We import the random module, which provides functions for random number generation.

We use the random.shuffle() function to shuffle the elements of the list original_list in-place. This means that the original list is modified directly.

We print the result, which is the list after shuffling its elements randomly.

39. Create a list of the first 10 factorial numbers.

In [ ]:
# Step 1: Define a function to calculate factorial
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Step 2: Use a loop to generate a list of the first 10 factorial numbers
factorial_numbers = [factorial(i) for i in range(10)]

# Step 3: Display the list of factorial numbers
print("The first 10 factorial numbers are:", factorial_numbers)


The first 10 factorial numbers are: [1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880]


We define a recursive function named factorial to calculate the factorial of a given number.
Use a Loop:

We use a list comprehension to generate a list (factorial_numbers) of the first 10 factorial numbers by calling the factorial function for each index in the range from 0 to 9.
Display the Result:

We print the result, which is the list of the first 10 factorial numbers.

40. Check if two lists have at least one element in common.

In [ ]:
# Example lists
list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]

# Step 1: Use set intersection to check for common elements
common_elements = set(list1) & set(list2)

# Step 2: Check if there is at least one common element
if common_elements:
    print("The lists have at least one common element.")
else:
    print("The lists do not have any common elements.")


The lists have at least one common element.


We start with two example lists, list1 and list2, containing integers.

We use set intersection (set(list1) & set(list2)) to find the common elements between the two lists. The & operator performs the intersection operation on sets.

We check if there is at least one common element by evaluating the set of common elements in a boolean context.

41. Remove all elements from a list.

In [ ]:
# Example list
my_list = [78,34,12,45,723,78]

# Use clear() method to remove all elements from a list
my_list.clear()

# Display the result
print(f"The list after removing all the elements is:",my_list)

The list after removing all the elements is: []


To remove all elements from a list, we can use the clear() method.



42. Replace negative numbers in a list with 0.

In [ ]:
# Example list
numbers = [56, -78, -99, 34, 79, 62, -83]

#Use list comprehension to replace negative numbers with 0
non_negative_numbers = [max(0, num) for num in numbers]

#Display the list with negative numbers replaced by 0
print("The list with negative numbers replaced by 0 is:", non_negative_numbers)

The list with negative numbers replaced by 0 is: [56, 0, 0, 34, 79, 62, 0]


We start with an example list named numbers containing integers.

We use list comprehension to iterate through numbers and replace each negative number with 0 using the max(0, num) function.

We print the result, which is the list with negative numbers replaced by 0.

43. Convert a string into a list of words.

In [ ]:
# Original string
sentence = " This is a sample sentence."

# Use the split() method to convert the string into a list of words
word_list = sentence.split()

# Display the list of words
print(f"The list of words is:",word_list)

The list of words is: ['This', 'is', 'a', 'sample', 'sentence.']


We start with an example string named sentence containing words.

We use the split() method on the string to convert it into a list of words. By default, split() splits the string at whitespace characters.

We print the result, which is the list of words.

44. Convert a list of words into a string.

In [ ]:
# Example list of words
word_list = ['This', 'is', 'a', 'sample', 'sentence.']

# Step 1: Use the join() method to convert the list into a string
sentence = ' '.join(word_list)

# Step 2: Display the resulting string
print("The resulting string is:", sentence)


The resulting string is: This is a sample sentence.


We start with an example list named word_list containing words.

We use the join() method on a space (`' ') to concatenate the words from the list into a string. The space is used as a separator between words.

We print the result, which is the string formed by joining the words.

45. Create a list of the first `n` powers of 2.

In [ ]:
# Define the value of n
n = 5

# Use list comprehension to create a list of the first n powers of 2
powers_of_2 = [2**i for i in range(n)]

# Display the list of powers of 2
print(f"The first {n} powers of 2 are:", powers_of_2)


The first 5 powers of 2 are: [1, 2, 4, 8, 16]


We define the value of n to specify the number of powers of 2 we want in the list.

We use list comprehension to generate a list (powers_of_2) by raising 2 to the power of each index i in the range from 0 to n-1.

We print the result, which is the list of the first n powers of 2.

46. Find the longest string in a list of strings.

In [ ]:
# Example list of strings
string_list = ["apple", "banana", "kiwi", "strawberry", "orange"]

# Step 1: Use the max() function with the len() function as the key
longest_string = max(string_list, key=len)

# Step 2: Display the longest string
print("The longest string is:", longest_string)


The longest string is: strawberry


We start with an example list named string_list containing strings of different lengths.

We use the max() function with key=len to find the string with the maximum length in the list. The len() function calculates the length of each string.

We print the result, which is the longest string in the list.

47. Find the shortest string in a list of strings.

In [ ]:
# Example list of strings
string_list = ["apple", "banana", "kiwi", "strawberry", "orange"]

# Step 1: Use the min() function with the len() function as the key
shortest_string = min(string_list, key=len)

# Step 2: Display the shortest string
print("The shortest string is:", shortest_string)


The shortest string is: kiwi


We start with an example list named string_list containing strings of different lengths.

We use the min() function with key=len to find the string with the minimum length in the list. The len() function calculates the length of each string.

We print the result, which is the shortest string in the list.

48. Create a list of the first `n` triangular numbers.

In [ ]:
# Define the value of n
n = 5

# Use list comprehension to create a list of the first n triangular numbers
triangular_numbers = [(i * (i + 1)) // 2 for i in range(1, n + 1)]

# Display the list of triangular numbers
print(f"The first {n} triangular numbers are:", triangular_numbers)


The first 5 triangular numbers are: [1, 3, 6, 10, 15]


We define the value of n to specify the number of triangular numbers we want in the list.

We use list comprehension to generate a list (triangular_numbers) by calculating the triangular number for each index i in the range from 1 to n.

We print the result, which is the list of the first n triangular numbers.

49. Check if a list contains another list as a subsequence.

In [ ]:
# Function to check if list `b` is a subsequence of list `a`
def is_subsequence(a, b):
    # Iterator for the larger list `a`
    iter_a = iter(a)

    # Check if each element in `b` is present in `a`
    return all(elem in iter_a for elem in b)

# Example lists
list_a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_b = [3, 6, 8]

# Check if list_b is a subsequence of list_a
result = is_subsequence(list_a, list_b)

# Display the result
if result:
    print("list_b is a subsequence of list_a.")
else:
    print("list_b is not a subsequence of list_a.")


list_b is a subsequence of list_a.


We define a function named is_subsequence that takes two lists (a and b) as arguments. It uses an iterator (iter_a) for the larger list a.

The function checks if each element in list b is present in list a using the all() function and a generator expression.

We print the result indicating whether list_b is a subsequence of list_a.

50. Swap two elements in a list by their indices.

In [ ]:
# Function to check if list `b` is a subsequence of list `a`
def is_subsequence(a, b):
    # Iterator for the larger list `a`
    iter_a = iter(a)

    # Check if each element in `b` is present in `a`
    return all(elem in iter_a for elem in b)

# Example lists
list_a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_b = [3, 6, 8]

# Check if list_b is a subsequence of list_a
result = is_subsequence(list_a, list_b)

# Display the result
if result:
    print("list_b is a subsequence of list_a.")
else:
    print("list_b is not a subsequence of list_a.")


list_b is a subsequence of list_a.


We define a function named is_subsequence that takes two lists (a and b) as arguments. It uses an iterator (iter_a) for the larger list a.

The function checks if each element in list b is present in list a using the all() function and a generator expression.

We print the result indicating whether list_b is a subsequence of list_a.

Tuple Based Practice Problem :

1. Create a tuple with integers from 1 to 5.

In [ ]:
# Create a tuple with integers from 1 to 5
my_tuple = (1,2,3,4,5)

# Display the created tuple
print(f"The created tuple is:",my_tuple)

The created tuple is: (1, 2, 3, 4, 5)


To create a tuple with integers from 1 to 5, you can use the tuple() constructor.

This result shows the tuple with integers from 1 to 5.

2. Access the third element of a tuple.

In [ ]:
# Example tuple
my_tuple = (1, 2, 3, 4, 5)

# Access the third element (index 2)
third_element = my_tuple[2]

# Display the third element
print("The third element of the tuple is:", third_element)


The third element of the tuple is: 3


To access the third element of a tuple in Python, you can use square brackets [] along with the index of the element you want.

This result shows how to access the third element (index 2) of a tuple.

3. Find the length of a tuple without using the `len()` function.

In [ ]:
# Example tuple
my_tuple = (1, 2, 3, 4, 5)

# Initialize a counter variable
tuple_length = 0

# Iterate through the tuple and count elements
for _ in my_tuple:
    tuple_length += 1

# Display the length of the tuple
print("The length of the tuple is:", tuple_length)


The length of the tuple is: 5


we can find the length of a tuple without using the len() function by using a loop to iterate through the elements.

Here, we use a loop to iterate through each element in the tuple and increment the tuple_length variable for each element. Finally, we print the length of the tuple.

4. Count the occurrences of an element in a tuple.

In [ ]:
# Example tuple
my_tuple = (1,2,3,4,2,5,2)

# Element to count occurrences
element_to_count = 2

# Count occurrences using the count() method
occurrences = my_tuple.count(element_to_count)

# Display the result
print(f"The element (element_to_count) occurs {occurrences} times in the tuple.")



The element (element_to_count) occurs 3 times in the tuple.


In [ ]:
# To count the occurrences of an element in a tuple in Python, you can use the count() method of the tuple.

# We use the count() method of the tuple my_tuple to count the occurrences of the specified element_to_count. The result is then displayed.

5. Find the index of the first occurrence of an element in a tuple.

In [ ]:
# Example tuple
my_tuple = (1, 2, 3, 4, 2, 5, 2)

# Element to find the index
element_to_find = 2

try:
    # Find the index using the index() method
    index_of_element = my_tuple.index(element_to_find)

    # Display the index of the first occurrence
    print(f"The index of the first occurrence of {element_to_find} is: {index_of_element}")
except ValueError:
    print(f"{element_to_find} is not present in the tuple.")


The index of the first occurrence of 2 is: 1


In [ ]:
# To find the index of the first occurrence of an element in a tuple.we can use the index() method of the tuple.

#We use the index() method of the tuple my_tuple to find the index of the specified element_to_find. The result is then displayed. Note that we use a try and except block to handle the case where the element is not present in the tuple.

#Adjust the element_to_find variable as needed for your specific case.



6. Check if an element exists in a tuple.

In [ ]:
# Example tuple
my_tuple = (1, 2, 3, 4, 5)

# Element to check
element_to_check = 3

# Step 1: Use the `in` keyword to check if the element exists
is_present = element_to_check in my_tuple

# Step 2: Display the result
if is_present:
    print(f"The element {element_to_check} exists in the tuple.")
else:
    print(f"The element {element_to_check} does not exist in the tuple.")


The element 3 exists in the tuple.


We start with an example tuple named my_tuple.

We specify the element_to_check that we want to check for in the tuple.

We use the in keyword to check if the element exists in the tuple. The result is stored in the is_present variable.

We print the result indicating whether the element exists in the tuple.

7. Convert a tuple to a list.

In [ ]:
# Example tuple
my_tuple = (33,44,22,55,66,77,99,88)

# Step 1: Use the list() constructor to convert the tuple to a list
my_list = list(my_tuple)

# Step 2: Display the resulting list
print("The converted list is:", my_list)


The converted list is: [33, 44, 22, 55, 66, 77, 99, 88]


We start with an example tuple named my_tuple.

We use the list() constructor to convert the tuple my_tuple to a list. The result is stored in the variable my_list.

We print the resulting list.

8. Convert a list to a tuple.

In [ ]:
# Example list
my_list = [23,33,43,53,63,73]

# Step 1: Use the tuple() constructor to convert the list to a tuple
my_tuple = tuple(my_list)

# Step 2: Display the resulting tuple
print("The converted tuple is:", my_tuple)


The converted tuple is: (23, 33, 43, 53, 63, 73)


We start with an example list named my_list.

We use the tuple() constructor to convert the list my_list to a tuple. The result is stored in the variable my_tuple.

We print the resulting tuple.

9. Unpack the elements of a tuple into variables.

In [ ]:
# Example tuple
my_tuple = (100,200,300)

# Unpack the tuple into variables
var1, var2, var3 = my_tuple

# Display the unpacked variables
print("Unpacked variables:", var1, var2, var3)


Unpacked variables: 100 200 300


We start with an example tuple named my_tuple containing three elements.

We use tuple unpacking to assign the values of the tuple to individual variables (var1, var2, var3).

We print the values of the unpacked variables.

10. Create a tuple of even numbers from 1 to 10.

In [ ]:
# Create a tuple of even numbers from 1 to 10
even_numbers_tuple = tuple(range(2, 11, 2))

# Display the created tuple
print("Tuple of even numbers:", even_numbers_tuple)


Tuple of even numbers: (2, 4, 6, 8, 10)


We use the range(2, 11, 2) to generate even numbers from 2 to 10 with a step of 2.

We use the tuple() constructor to convert the range of even numbers to a tuple.

We print the created tuple of even numbers.

11. Create a tuple of odd numbers from 1 to 10.

In [ ]:
# Create a tuple of odd numbers from 1 to 10
odd_numbers_tuple = tuple(range(1, 11, 2))

# Display the created tuple
print("Tuple of odd numbers:", odd_numbers_tuple)


Tuple of odd numbers: (1, 3, 5, 7, 9)


We use the range(1, 11, 2) to generate odd numbers from 1 to 9 with a step of 2.

We use the tuple() constructor to convert the range of odd numbers to a tuple.

We print the created tuple of odd numbers.

12. Concatenate two tuples.

In [ ]:
# First tuple
tuple1 = (65,87,95,23)

# Second tuple
tuple2 = (45,78,788,23)

#Concatenate the tuples using + operator
concatenated_tuple = tuple1 + tuple2

# Display the concatenated tuple
print(f"Concatenated tuples:", concatenated_tuple)

Concatenated tuples: (65, 87, 95, 23, 45, 78, 788, 23)


We have a tuple named tuple1 with elements (1, 2, 3).

We have another tuple named tuple2 with elements (4, 5, 6).

We use the + operator to concatenate tuple1 and tuple2 into a new tuple named concatenated_tuple.

We print the concatenated tuple.

13. Repeat a tuple three times.

In [ ]:
# Original tuple
original_tuple = (45,67,43)

# Repeat the tuple three times
repeated_tuple = original_tuple * 3

# Display the repeated tuple
print(f"Repeated tuple:", repeated_tuple)


Repeated tuple: (45, 67, 43, 45, 67, 43, 45, 67, 43)


We start with an original tuple named original_tuple with elements (1, 2, 3).

We use the * operator to repeat the original tuple three times, creating a new tuple named repeated_tuple.

We print the repeated tuple.

14. Check if a tuple is empty.

In [ ]:
# Exaple tuple
my_tuple = ()

# Check if the tuple is empty
if not my_tuple:
    print("The tuple is empty")
else:
    print("The tuple is not empty")


The tuple is empty


We start with an example tuple named my_tuple that is empty.

We use a conditional check (if not my_tuple) to determine if the tuple is empty. The not operator is used to check for negation.

We print whether the tuple is empty or not based on the result of the conditional check.

15. Create a nested tuple.

In [ ]:
# Create a nested tuple
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

# Display the nested tuple
print("Nested tuple:",nested_tuple)

Nested tuple: ((1, 2, 3), ('a', 'b', 'c'), (True, False))


We create a tuple named nested_tuple where each element is itself a tuple.
Display the Result:

We print the nested tuple.

16. Access the first element of a nested tuple.

In [ ]:
# Nested tuple
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

# Access the first element of the nested tuple
first_element = nested_tuple[0]

# Display the first element
print("The first element of a nested tuple:",first_element)

The first element of a nested tuple: (1, 2, 3)


We have a nested tuple named nested_tuple containing three tuples as elements.

We use indexing (nested_tuple[0]) to access the first element of the nested tuple. In this case, the first element is itself a tuple.

We print the first element of the nested tuple.

17. Create a tuple with a single element.

In [ ]:
# Tuple with a single element
single_element_tuple = (78,)

# Display the tuple
print("Tuple with a single element:",single_element_tuple)

Tuple with a single element: (78,)


We create a tuple named single_element_tuple with a single element (78). The important part is the trailing comma after the element.

We print the tuple with a single element.

18. Compare two tuples.

In [ ]:
# First tuple
tuple1 = (94,67,87)

# Second tuple
tuple2 = (94,67,87)

# Compare the tuples
if tuple1 == tuple2:
    print("The tuples are equal.")
else:
    print("The tuples are not equal.")



The tuples are equal.


We have a tuple named tuple1 with elements (94,67,87).
Second Tuple:

We have another tuple named tuple2 with the same elements (94,67,87).
Compare Tuples:

We use the == operator to check if the tuples are equal element-wise.
Display the Result:

We print whether the tuples are equal or not.

19. Delete a tuple.

In [ ]:
# Example tuple
my_tuple = (1, 2, 3, 4, 5)

# Display the original tuple
print("Original tuple:", my_tuple)

# Delete the entire tuple
del my_tuple

# Try to display the tuple after deletion (will result in an error)
try:
    print("After deletion:", my_tuple)
except NameError as e:
    print(f"Error: {e}")


Original tuple: (1, 2, 3, 4, 5)
Error: name 'my_tuple' is not defined


We start with an example tuple named my_tuple.

We print the original tuple before deletion.

We use the del statement to delete the entire tuple.

We attempt to print the tuple after deletion, but this will result in a NameError since the tuple no longer exists.

20. Slice a tuple.

In [ ]:
# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Slice the tuple to create a new tuple
sliced_tuple = original_tuple[1:4]

# Display the sliced tuple
print("Sliced tuple:", sliced_tuple)


Sliced tuple: (2, 3, 4)


We start with an example tuple named original_tuple.

We use the slice notation [1:4] to create a new tuple (sliced_tuple) containing elements from index 1 to 3 (exclusive).

We print the new tuple created by slicing the original tuple.

21. Find the maximum value in a tuple.

In [ ]:
# Example tuple
my_tuple = (10, 5, 8, 20, 15)

# Find the maximum value in the tuple
max_value = max(my_tuple)

# Display the maximum value
print("The maximum value in the tuple:",max_value)

The maximum value in the tuple: 20


We start with an example tuple named my_tuple.

We use the max() function to find the maximum value in the tuple.

We print the maximum value.

22. Find the minimum value in a tuple.

In [ ]:
# Example tuple
my_tuple = (10, 5, 8, 20, 15)

# Find the minimum value in the tuple
min_value = min(my_tuple)

# Diplay the minimum value
print("The minimum value in the tuple:",min_value)

The minimum value in the tuple: 5


We start with an example tuple named my_tuple.

We use the min() function to find the minimum value in the tuple.

We print the minimum value.

23. Convert a string to a tuple of characters.

In [ ]:
# Example string
my_string = "hello"

# Convert the string to a tuple of characters
tuple_of_characters = tuple(iter(my_string))

# Display the tuple of characters
print("The tuple of characters:",tuple_of_characters)

The tuple of characters: ('h', 'e', 'l', 'l', 'o')


We start with an example string named my_string.

We use the iter() function to create an iterator from the string, and then we use the tuple() constructor to convert the iterator to a tuple of characters.

We print the tuple of characters.

24. Convert a tuple of characters to a string.

In [ ]:
# Example tuple of characters
tuple_of_characters = ('h', 'e', 'l', 'l', 'o')

# Convert the tuple to a string
resulting_string = ''.join(tuple_of_characters)

# Display the resulting string
print("Resulting string:",resulting_string)

Resulting string: hello


We start with an example tuple of characters named tuple_of_characters.

We use the join() method to concatenate the characters in the tuple into a string. The empty string '' is used as the separator.

We print the resulting string.

25. Create a tuple from multiple data types.

In [ ]:
# Example tuple with multiple data types
mixed_tuple = (1, 'hello', 3.14, True)

# Display the mixed tuple
print("Mixed tuple:", mixed_tuple)


Mixed tuple: (1, 'hello', 3.14, True)


We create an example tuple named mixed_tuple containing elements of different data types, including an integer, a string, a float, and a boolean.

We print the mixed tuple.

26. Check if two tuples are identical.

In [ ]:
# First tuple
tuple1 = (1, 'hello', 3.14, True)

# Second tuple
tuple2 = (1, 'hello', 3.14, True)

# Check if the tuples are identical
if tuple1 == tuple2:
    print("The tuples are identical.")
else:
    print("The tuples are not identical.")


The tuples are identical.


We have a tuple named tuple1 with elements of different data types.

We have another tuple named tuple2 with the same elements.

We use the == operator to check if the tuples are identical element-wise.

We print whether the tuples are identical or not.

27. Sort the elements of a tuple.

In [ ]:
# Example tuple
my_tuple = (5, 2, 8, 1, 3)

# Create a sorted list from the tuple elements
sorted_list = sorted(my_tuple)

# Convert the sorted list back to a tuple
sorted_tuple = tuple(sorted_list)

# Display the sorted tuple
print("Sorted tuple:", sorted_tuple)


Sorted tuple: (1, 2, 3, 5, 8)


We start with an example tuple named my_tuple containing numeric elements.

We use the sorted() function to create a sorted list from the elements of the tuple.

We use the tuple() constructor to convert the sorted list back to a tuple.

We print the sorted tuple.

28. Convert a tuple of integers to a tuple of strings.

In [ ]:
# Example tuple of integers
tuple_of_integers = (1, 2, 3, 4, 5)

# Convert the tuple of integers to a tuple of strings using map()
tuple_of_strings = tuple(map(str, tuple_of_integers))

# Display the tuple of strings
print("Tuple of strings:", tuple_of_strings)


Tuple of strings: ('1', '2', '3', '4', '5')


We start with an example tuple named tuple_of_integers containing integer elements.

We use the map() function to apply the str function to each element in the tuple, converting them to strings.

We use the tuple() constructor to convert the resulting map object to a tuple.

We print the tuple of strings.

29. Convert a tuple of strings to a tuple of integers.

In [ ]:
# Example tuple of strings
tuple_of_strings = ('1', '2', '3', '4', '5')

# Convert the tuple of strings to a tuple of integers using map()
tuple_of_integers = tuple(map(int, tuple_of_strings))

# Display the tuple of integers
print("Tuple of integers:", tuple_of_integers)


Tuple of integers: (1, 2, 3, 4, 5)


We start with an example tuple named tuple_of_strings containing string elements.

We use the map() function to apply the int function to each element in the tuple, converting them to integers.

We use the tuple() constructor to convert the resulting map object to a tuple.

We print the tuple of integers.

30. Merge two tuples.

In [ ]:
# First tuple
tuple1 = (1, 2, 3)

# Second tuple
tuple2 = ('a', 'b', 'c')

# Merge the tuples using the + operator
merged_tuple = tuple1 + tuple2

# Display the merged tuple
print("Merged tuple:", merged_tuple)


Merged tuple: (1, 2, 3, 'a', 'b', 'c')


We have a tuple named tuple1 with numeric elements.

We have another tuple named tuple2 with string elements.

We use the + operator to concatenate tuple1 and tuple2 into a new tuple named merged_tuple.

We print the merged tuple.

31. Flatten a nested tuple.

In [ ]:
def flatten_tuple(nested_tuple):
    flat_list = []
    for item in nested_tuple:
        if isinstance(item, tuple):
            flat_list.extend(flatten_tuple(item))
    else:
        flat_list.append(item)
    return flat_list

# Example nested tuple
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

# Flatten the nested tuple
flattened_tuple = tuple(flatten_tuple(nested_tuple))

# Display the flattened tuple
print("flattened tuple:", flattened_tuple)


flattened tuple: (3, 'c', False, (True, False))


We define a recursive function flatten_tuple that takes a tuple as input and flattens it.

We have an example nested tuple named nested_tuple with inner tuples.

We call the flatten_tuple function to flatten the nested tuple.

We use the tuple() constructor to convert the flattened list back to a tuple.

We print the flattened tuple.

32. Create a tuple of the first 5 prime numbers.

In [ ]:
# Manually create a tuple of the first 5 prime numbers
prime_numbers_tuple = (2, 3, 5, 7, 11)

# Display the tuple of prime numbers
print("Tuple of the first 5 prime numbers:", prime_numbers_tuple)


Tuple of the first 5 prime numbers: (2, 3, 5, 7, 11)


To create a tuple of the first 5 prime numbers, We can manually specify the values or use a loop to generate them. Here we used manually specified tuple

This result shows manually specifying the values.

33. Check if a tuple is a palindrome.

In [ ]:
def is_palindrome(my_tuple):
    return my_tuple == my_tuple[::-1]

# Example tuples
palindrome_tuple = (1,2,3,2,1)
non_palindrome_tuple = (1,2,3,4,5)

# Check if the tuples are palindromes
print("Is palindrome:", is_palindrome(palindrome_tuple))
print("Is palindrome:", is_palindrome(non_palindrome_tuple))


Is palindrome: True
Is palindrome: False


We define a function is_palindrome that takes a tuple as input and returns True if it is a palindrome and False otherwise.

We have two example tuples, palindrome_tuple and non_palindrome_tuple.

We use the is_palindrome function to check if each tuple is a palindrome.

We print whether each tuple is a palindrome.

34. Create a tuple of squares of numbers from 1 to 5.

In [ ]:
# Create a tuple of squares using a tuple comprehension
squares_tuple = tuple(x**2 for x in range(1, 6))

# Display the tuple of squares
print("Tuple of squares:", squares_tuple)


Tuple of squares: (1, 4, 9, 16, 25)


We use a tuple comprehension to create a tuple of squares.

We use range(1, 6) to generate numbers from 1 to 5 (inclusive).

For each number in the range, we calculate its square using x**2.

We use the tuple() constructor to convert the list of squares to a tuple.

We print the tuple of squares.

35. Filter out all even numbers from a tuple.

In [ ]:
# Example tuple
original_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Filter out even numbers using a tuple comprehension
filtered_tuple = tuple(x for x in original_tuple if x % 2 != 0)

# Display the filtered tuple
print("Filtered tuple:", filtered_tuple)


Filtered tuple: (1, 3, 5, 7, 9)


We start with an example tuple named original_tuple containing integers.

We use a tuple comprehension to create a new tuple (filtered_tuple) by including only the odd numbers from the original tuple.

We print the filtered tuple.

36. Multiply all elements in a tuple by 2.

In [ ]:
# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Multiply all elements by 2 using a tuple comprehension
doubled_tuple = tuple( x * 2 for x in original_tuple)

# Display the doubled tuple
print("Doubled tuple:", doubled_tuple)

Doubled tuple: (2, 4, 6, 8, 10)


We start with an example tuple named original_tuple containing integers.

Using a tuple comprehension or the map() function, we multiply each element by 2.

We print the doubled tuple.

37. Create a tuple of random numbers.

In [ ]:
import random

# Generate a tuple of 5 random numbers between 1 and 100
random_tuple = tuple(random.randint(1, 100) for _ in range(5))

# Display the tuple of random numbers
print(f"Random tuple:",random_tuple)

Random tuple: (37, 48, 3, 97, 77)


We import the random module to access functions for generating random numbers.

Using a tuple comprehension, we generate a tuple of 5 random numbers using random.randint(1, 100). Adjust the range or the number of elements as needed.

We print the tuple of random numbers.

38. Check if a tuple is sorted.

In [ ]:
# Function to check if a tuple is sorted
def is_sorted(my_tuple):
    return all(my_tuple[i] <= my_tuple[i+1] for i in range(len(my_tuple)-1))

# Example tuples
sorted_tuple = (1, 2, 3, 4, 5)
unsorted_tuple = (3, 1, 4, 1, 5)

# Check if the tuples are sorted
print("Is sorted:", is_sorted(sorted_tuple))
print("Is sorted:", is_sorted(unsorted_tuple))


Is sorted: True
Is sorted: False


We define a function is_sorted that takes a tuple as input and returns True if it is sorted and False otherwise.

We have two example tuples, sorted_tuple and unsorted_tuple.

We use the is_sorted function to check if each tuple is sorted.

We print whether each tuple is sorted.

39. Rotate a tuple to the left by `n` positions.

In [ ]:
def rotate_left(my_tuple, n):
    n = n % len(my_tuple)  # Ensure n is within the length of the tuple
    return my_tuple[n:] + my_tuple[:n]

# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Rotate the tuple to the left by 2 positions
rotated_tuple = rotate_left(original_tuple, 2)

# Display the rotated tuple
print("Rotated tuple:", rotated_tuple)




Rotated tuple: (3, 4, 5, 1, 2)


We define a function rotate_left that takes a tuple and an integer n as input and rotates the tuple to the left by n positions.

We use n % len(my_tuple) to ensure that n is within the length of the tuple. This is done to handle cases where n is larger than the length of the tuple.

We use slicing to create a new tuple by concatenating the elements after position n with the elements before position n.

We print the rotated tuple.

40. Rotate a tuple to the right by `n` positions.

In [ ]:
def rotate_right(my_tuple, n):
    n = n % len(my_tuple)  # Ensure n is within the length of the tuple
    return my_tuple[-n:] + my_tuple[:-n]

# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Rotate the tuple to the right by 2 positions
rotated_tuple = rotate_right(original_tuple, 2)

# Display the rotated tuple
print("Rotated tuple:", rotated_tuple)


Rotated tuple: (4, 5, 1, 2, 3)


We define a function rotate_right that takes a tuple and an integer n as input and rotates the tuple to the right by n positions.

We use n % len(my_tuple) to ensure that n is within the length of the tuple. This is done to handle cases where n is larger than the length of the tuple.

We use slicing to create a new tuple by concatenating the elements after the position -n (equivalent to len(my_tuple) - n) with the elements before the position -n.

We print the rotated tuple.

41. Create a tuple of the first 5 Fibonacci numbers.

In [ ]:
# Function to generate the first n Fibonacci numbers
def generate_fibonacci(n):
    fibonacci_sequence = [0, 1]
    while len(fibonacci_sequence) < n:
        next_number = fibonacci_sequence[-1] + fibonacci_sequence[-2]
        fibonacci_sequence.append(next_number)
    return tuple(fibonacci_sequence)

# Generate a tuple of the first 5 Fibonacci numbers
fibonacci_tuple = generate_fibonacci(5)

# Display the tuple of Fibonacci numbers
print("Fibonacci tuple:", fibonacci_tuple)


Fibonacci tuple: (0, 1, 1, 2, 3)


We define a function generate_fibonacci that takes an integer n as input and generates the first n Fibonacci numbers.

We start with the initial Fibonacci sequence [0, 1].

We use a loop to generate the Fibonacci sequence until its length reaches n.

We use the tuple() constructor to convert the list of Fibonacci numbers to a tuple.

We print the tuple of the first 5 Fibonacci numbers.

42. Create a tuple from user input.

In [ ]:
# Get user input for a comma-separated list of elements
user_input = input("Enter elements separated by commas: ")

# Convert the input string into a tuple
user_tuple = tuple(map(int, user_input.split(',')))

# Display the user-created tuple
print("User-created tuple:", user_tuple)


Enter elements separated by commas:  1,2,78,90


User-created tuple: (1, 2, 78, 90)


We use the input() function to get user input. The user is expected to enter a comma-separated list of elements.

We use the split(',') method to split the input string into a list of elements using commas as separators.

We use the map(int, ...) to convert each element to an integer.

Finally, we use tuple() to create a tuple from the list of integers.

We print the tuple created from the user's input.

43. Swap two elements in a tuple.

In [ ]:
# Function to swap two elements in a tuple
def swap_elements(my_tuple, index1, index2):
    # Convert the tuple to a list to allow modification
    mutable_list = list(my_tuple)

    # Swap the elements at the specified indices
    mutable_list[index1], mutable_list[index2] = mutable_list[index2], mutable_list[index1]

    # Convert the list back to a tuple
    new_tuple = tuple(mutable_list)

    return new_tuple

# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Swap elements at indices 1 and 3
swapped_tuple = swap_elements(original_tuple, 1, 3)

# Display the original and swapped tuples
print("Original tuple:", original_tuple)
print("Swapped tuple:", swapped_tuple)


Original tuple: (1, 2, 3, 4, 5)
Swapped tuple: (1, 4, 3, 2, 5)


We define a function swap_elements that takes a tuple, and two indices as input and returns a new tuple with the elements at the specified indices swapped.

We convert the input tuple to a list to allow modification.

We swap the elements at the specified indices in the list.

We convert the modified list back to a tuple.

We print the original and swapped tuples.

44. Reverse the elements of a tuple.

In [ ]:
# Function to reverse the elements of a tuple
def reverse_tuple(my_tuple):
    return my_tuple[::-1]

# Example tuple
original_tuple = (1, 2, 3, 4, 5)

# Reverse the elements of the tuple
reversed_tuple = reverse_tuple(original_tuple)

# Display the original and reversed tuples
print("Original tuple:", original_tuple)
print("Reversed tuple:", reversed_tuple)


Original tuple: (1, 2, 3, 4, 5)
Reversed tuple: (5, 4, 3, 2, 1)


We define a function reverse_tuple that takes a tuple as input and returns a new tuple with its elements reversed using slicing.

We use my_tuple[::-1] to create a new tuple with the elements in reverse order.

We print the original and reversed tuples.

45. Create a tuple of the first `n` powers of 2.

In [ ]:
# Function to generate the first n powers of 2
def generate_powers_of_2(n):
    return tuple(2 ** i for i in range(n))

# Example: Generate the first 5 powers of 2
powers_of_2_tuple = generate_powers_of_2(5)

# Display the tuple of powers of 2
print("Powers of 2 tuple:", powers_of_2_tuple)


Powers of 2 tuple: (1, 2, 4, 8, 16)


We define a function generate_powers_of_2 that takes an integer n as input and generates the first n powers of 2.

We use a list comprehension to generate the powers of 2 by iterating from 0 to n-1.

We use the tuple() constructor to convert the list of powers of 2 to a tuple.

We print the tuple of the first 5 powers of 2.

46. Find the longest string in a tuple of strings.

In [ ]:
# Function to find the longest string in a tuple
def find_longest_string(string_tuple):
    return max(string_tuple, key=len)

# Example tuple of strings
string_tuple = ("apple", "banana", "kiwi", "strawberry", "orange")

# Find the longest string in the tuple
longest_string = find_longest_string(string_tuple)

# Display the original tuple and the longest string
print("Original tuple:", string_tuple)
print("Longest string:", longest_string)


Original tuple: ('apple', 'banana', 'kiwi', 'strawberry', 'orange')
Longest string: strawberry


We define a function find_longest_string that takes a tuple of strings and uses the max() function with key=len to find the string with the maximum length.

The max() function is used to find the maximum element in the tuple based on the length of each string (key=len).

We print the original tuple of strings and the longest string.

47. Find the shortest string in a tuple of strings.

In [ ]:
# Function to find the shortest string in a tuple
def find_shortest_string(string_tuple):
    return min(string_tuple, key=len)

# Example tuple of strings
string_tuple = ("apple", "banana", "kiwi", "strawberry", "orange")

# Find the shortest string in the tuple
shortest_string = find_shortest_string(string_tuple)

# Display the original tuple and the shortest string
print("Original tuple:", string_tuple)
print("Shortest string:", shortest_string)


Original tuple: ('apple', 'banana', 'kiwi', 'strawberry', 'orange')
Shortest string: kiwi


We define a function find_shortest_string that takes a tuple of strings and uses the min() function with key=len to find the string with the minimum length.

The min() function is used to find the minimum element in the tuple based on the length of each string (key=len).

We print the original tuple of strings and the shortest string.

48. Create a tuple of the first `n` triangular numbers.

In [ ]:
# Function to generate the first n triangular numbers
def generate_triangular_numbers(n):
    return tuple((i * (i + 1)) // 2 for i in range(1, n + 1))

# Example: Generate the first 5 triangular numbers
triangular_numbers_tuple = generate_triangular_numbers(5)

# Display the tuple of triangular numbers
print("Triangular numbers tuple:", triangular_numbers_tuple)


Triangular numbers tuple: (1, 3, 6, 10, 15)


We define a function generate_triangular_numbers that takes an integer n as input and generates the first n triangular numbers.

We use a list comprehension to generate the triangular numbers by iterating from 1 to n.

We use the tuple() constructor to convert the list of triangular numbers to a tuple.

We print the tuple of the first 5 triangular numbers.

49. Check if a tuple contains another tuple as a subsequence.

In [ ]:
# Function to check if a tuple contains another tuple as a subsequence
def contains_subsequence(main_tuple, sub_tuple):
    m, n = len(main_tuple), len(sub_tuple)

    for i in range(m - n + 1):
        if main_tuple[i:i + n] == sub_tuple:
            return True

    return False

# Example tuples
main_tuple = (1, 2, 3, 4, 5, 6, 7, 8)
sub_tuple = (3, 4, 5)

# Check if the main tuple contains the subsequence
result = contains_subsequence(main_tuple, sub_tuple)

# Display the result
print("Main tuple:", main_tuple)
print("Sub tuple:", sub_tuple)
print("Contains subsequence:", result)


Main tuple: (1, 2, 3, 4, 5, 6, 7, 8)
Sub tuple: (3, 4, 5)
Contains subsequence: True


We define a function contains_subsequence that takes two tuples as input and checks if the first tuple contains the second tuple as a subsequence.

We use a loop to iterate through the elements of the larger tuple (main_tuple) and check for a subsequence match with the smaller tuple (sub_tuple).

We compare slices of the larger tuple to the smaller tuple to check for a subsequence match.

We print the main tuple, sub tuple, and the result of whether the main tuple contains the subsequence.

50. Create a tuple of alternating 1s and 0s of length `n`.

In [ ]:
# Function to create a tuple of alternating 1s and 0s
def alternating_ones_zeros_tuple(n):
    return tuple(i % 2 for i in range(n))

# Example: Create a tuple of alternating 1s and 0s of length 8
alternating_tuple = alternating_ones_zeros_tuple(8)

# Display the tuple
print("Alternating tuple:", alternating_tuple)


Alternating tuple: (0, 1, 0, 1, 0, 1, 0, 1)


We define a function alternating_ones_zeros_tuple that takes an integer n as input and generates a tuple of alternating 1s and 0s.

We use a list comprehension to generate the alternating sequence by using the modulo operator % to determine whether to insert 1 or 0.

We use the tuple() constructor to convert the list of alternating 1s and 0s to a tuple.

We print the tuple of alternating 1s and 0s.

Set Based Practice Problem :

1. Create a set with integers from 1 to 5.

In [ ]:
# Create a set with integers from 1 to 5 using curly braces
my_set = {1,2,3,4,5,6}

# Display set
print("Set:", my_set)

Set: {1, 2, 3, 4, 5, 6}


We can use curly braces {} constructor.
    
Both approaches will result in the same set containing integers from 1 to 5.

2. Add an element to a set.

In [ ]:
# Create a set
my_set = {5,6,854,546,34}

# Add an element (e.g., 108) to the set using the add() method
my_set.add(108)

# Display the updated set
print("Updated Set:", my_set)

Updated Set: {546, 34, 5, 6, 854, 108}


To add an element to a set in Python, you can use the add() method.

In this example, the add(108) method adds the element 108 to the set.



3. Remove an element from a set.

In [ ]:
# Create a set
my_set = {56,26,87,92,45}

# Remove an element (e.g., 26) from the set using the remove() method
my_set.remove(26)

# Display the updated set
print("Updated set:", my_set)

Updated set: {87, 56, 92, 45}


To remove an element from a set, you can use the remove() method.

In this example, the remove(26) method removes the element 3 from the set.

It's important to note that if the specified element is not present in the set, the remove() method will raise a KeyError.



4. Check if an element exists in a set.

In [ ]:
# Create a set
my_set = {74,84,12,2,67}

# Check if an element (e.g., 3) exists in the set using the in operator
element_to_check = 2
if element_to_check in my_set:
    print(f"{element_to_check} exists in the set.")
else:
    print(f"{element_to_check} does not exists in the set.")

2 exists in the set.


To check if an element exists in a set,we can use the in operator.

The in operator is used to check if the element 3 exists in the set.



5. Find the length of a set without using the `len()` function.

In [ ]:
# Create a set
my_set = {9,8,7,6,5}

# Find the length of the set without using len()
length = 0
for _ in my_set:
    length += 1

# Display the length of the set
print("Length of the set:",length)


Length of the set: 5


To find the length of a set without using the len() function, we can use a loop to iterate through the set and count the number of elements.

We use a loop to iterate through each element in the set, and for each element, we increment the length variable.

After the loop, the length variable will contain the count of elements in the set.



6. Clear all elements from a set.

In [ ]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Clear all elements from the set using the clear() method
my_set.clear()

# Display the updated set
print("Updated set:", my_set)

Updated set: set()


To clear all elements from a set, we can use the clear() method.

The clear() method is called on the set (my_set), which removes all elements from the set, leaving it empty.

The set() in the output indicates that the set is now empty. Adjust the set variable name as needed for your specific case.

7. Create a set of even numbers from 1 to 10.

In [ ]:
# Create a set of even numbers from 1 to 10 using a set comprehension
even_numbers_set = {x for x in range(1, 11) if x % 2 == 0}

# Display the set
print("Set of even numbers:", even_numbers_set)


Set of even numbers: {2, 4, 6, 8, 10}


To create a set of even numbers from 1 to 10, we can use a set comprehension.

The set comprehension {x for x in range(1, 11) if x % 2 == 0} generates a set containing even numbers from 1 to 10.



8. Create a set of odd numbers from 1 to 10.

In [ ]:
# Create a set of odd numbers from 1 to 10 using a set comprehension
odd_numbers_set = {x for x in range(1, 11) if x % 2 != 0}

# Display the set
print("Set of odd numbers:", odd_numbers_set)


Set of odd numbers: {1, 3, 5, 7, 9}


To create a set of odd numbers from 1 to 10, we can use a set comprehension.

The set comprehension {x for x in range(1, 11) if x % 2 != 0} generates a set containing odd numbers from 1 to 10.



9. Find the union of two sets.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Find the union of the two sets using the | operator
union_set = set1 | set2

# Display the union set
print("Union set:", union_set)



Union set: {1, 2, 3, 4, 5, 6, 7, 8}


To find the union of two sets,we can use the pipe operator.

The union set contains all unique elements from both set1 and set2.


10. Find the intersection of two sets.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Find the intersection of the two sets using the & operator
intersection_set = set1 & set2

# Display the intersection set
print("Intersection set:", intersection_set)


Intersection set: {4, 5}


We can use the & (ampersand) operator.

The intersection set contains the common elements between set1 and set2.

11. Find the difference between two sets.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Find the difference between set1 and set2 using the - operator
difference_set = set1 - set2

# Display the difference set
print("Difference set:", difference_set)


Difference set: {1, 2, 3}


We can use the - (minus) operator.

The difference set contains elements that are in set1 but not in set2.

12. Check if a set is a subset of another set.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {1, 2, 3}

# Check if set2 is a subset of set1 using the <= operator
is_subset = set2 <= set1

# Display the result
print(f"Is set2 a subset of set1? {is_subset}")


Is set2 a subset of set1? True


To check if a set is a subset of another set, we can use the <= (less than or equal to) operator.

The result will be True because all elements of set2 are present in set1.

13. Check if a set is a superset of another set.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {1, 2, 3}

# Check if set1 is a superset of set2 using the >= operator
is_superset = set1 >= set2

# Display the result
print(f"Is set1 a superset of set2? {is_superset}")


Is set1 a superset of set2? True


To check if a set is a superset of another set, we can use the >= (greater than or equal to) operator.

The result will be True because all elements of set2 are present in set1.

14. Create a set from a list.

In [ ]:
# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a set from the list using the set() constructor
my_set = set(my_list)

# Display the set
print("Set from a list:",my_set)

Set from a list: {1, 2, 3, 4, 5}


To create a set from a list, we can use the set() constructor.

The set(my_list) constructs a set containing the unique elements from the list my_list.

15. Convert a set to a list.

In [ ]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Convert the set to a list using the list() constructor
my_list = list(my_set)

# Display the list
print("List from set:",my_list)

List from set: [1, 2, 3, 4, 5]


To convert a set to a list in Python, you can use the list() constructor.

The list(my_set) constructs a list containing the elements of the set my_set.



16. Remove a random element from a set.

In [ ]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Remove a random element from the set using the pop() method
removed_element = my_set.pop()

# Display the removed element and the updated set
print("Removed Element:", removed_element)
print("Updated Set:", my_set)


Removed Element: 1
Updated Set: {2, 3, 4, 5}


To remove a random element from a set, we can use the pop() method.

The pop() method removes and returns an arbitrary (random) element from the set.

The pop() method is used to remove a random element from the set my_set.

If the set is empty, calling pop() will raise a KeyError. Ensure that the set is not empty before using pop().

17. Pop an element from a set.

In [ ]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Pop an element from the set using the pop() method
popped_element = my_set.pop()

# Display the popped element and the updated set
print("Popped Element:", popped_element)
print("Updated Set:", my_set)


Popped Element: 1
Updated Set: {2, 3, 4, 5}


To pop an element from a set, we can use the pop() method. The pop() method removes and returns an arbitrary (random) element from the set.

The pop() method is used to pop an arbitrary element from the set my_set.

If the set is empty, calling pop() will raise a KeyError. Ensure that the set is not empty before using pop().

18. Check if two sets have no elements in common.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {6, 7, 8, 9, 10}

# Check if the sets have no elements in common using isdisjoint()
are_disjoint = set1.isdisjoint(set2)

# Display the result
print(f"Are the sets disjoint? {are_disjoint}")

Are the sets disjoint? True


To check if two sets have no elements in common, we can use the isdisjoint() method.

The isdisjoint() method returns True if two sets have no elements in common and False otherwise.

This means that the sets have no elements in common. If the result were False, it would indicate that the sets have at least one element in common.

19. Find the symmetric difference between two sets.

In [ ]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Find the symmetric difference between set1 and set2 using the ^ operator
symmetric_difference_set = set1 ^ set2

# Display the symmetric difference set
print("Symmetric Difference set:", symmetric_difference_set)


Symmetric Difference set: {1, 2, 3, 6, 7, 8}


To find the symmetric difference between two sets, we can use the ^ (caret) operator.

The symmetric difference set contains elements that are in either set1 or set2, but not in both.

20. Update a set with elements from another set.

In [ ]:
# Create two sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Update set1 with elements from set2 using the update() method
set1.update(set2)

# Display the updated set1
print("Updated Set1:", set1)


Updated Set1: {1, 2, 3, 4, 5}


21. Create a set of the first 5 prime numbers.

In [ ]:
# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find the first 5 prime numbers
first_5_primes = set()
number = 2  # Start with the first prime number
while len(first_5_primes) < 5:
    if is_prime(number):
        first_5_primes.add(number)
    number += 1

# Print the set of the first 5 prime numbers
print(first_5_primes)


{2, 3, 5, 7, 11}


This code defines a function is_prime to check if a given number is prime.

It then iterates through numbers, starting from 2, and adds them to the set first_5_primes if they are prime.

The loop continues until the set has 5 prime numbers. Finally, it prints the set of the first 5 prime numbers.

22. Check if two sets are identical.

In [ ]:
# Example sets
set1 = {1, 2, 3, 4, 5}
set2 = {5, 4, 3, 2, 1}

# Using the == operator
if set1 == set2:
    print("The sets are identical.")
else:
    print("The sets are not identical.")




The sets are identical.


set1 and set2 contain the same elements, but they are in a different order.

The == operator checks if the sets have the same elements, regardless of their order.

Approaches will output "The sets are identical" for the provided sets.

23. Create a frozen set.

In [ ]:
# Create a regular set
my_set = {1, 2, 3, 4, 5}

# Create a frozen set
my_frozen_set = frozenset(my_set)

# Print the original set and the frozen set
print("Original set:", my_set)
print("Frozen set:", my_frozen_set)


Original set: {1, 2, 3, 4, 5}
Frozen set: frozenset({1, 2, 3, 4, 5})


my_set is a regular set, and my_frozen_set is a frozen set created using frozenset(my_set).

Remember that while regular sets are mutable (you can add or remove elements), frozen sets are immutable.

Once a frozen set is created, you cannot modify it by adding or removing elements.

24. Check if a set is disjoint with another set.

In [ ]:
# Example sets
set1 = {1, 2, 3, 4, 5}
set2 = {6, 7, 8, 9, 10}

# Check if the sets are disjoint
if set1.isdisjoint(set2):
    print("The sets are disjoint.")
else:
    print("The sets have common elements.")


The sets are disjoint.


We can use the isdisjoint() method to check if one set is disjoint with another set.

Two sets are disjoint if they have no elements in common.

set1 and set2 are disjoint because they have no elements in common.

The isdisjoint() method returns True if the sets are disjoint and False otherwise.

If the sets had common elements, the output would be "The sets have common elements."

25. Create a set of squares of numbers from 1 to 5.

In [ ]:
# Create a set of squares of numbers from 1 to 5
squares_set = {x**2 for x in range(1, 6)}

# Print the set of squares
print(squares_set)


{1, 4, 9, 16, 25}


The set comprehension {x**2 for x in range(1, 6)} generates the squares of numbers from 1 to 5 (inclusive).

The resulting set, squares_set, will contain {1,4,9,16,25}, which are the squares of 1, 2, 3, 4, and 5, respectively.

26. Filter out all even numbers from a set.

In [ ]:
# Original set
original_set = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

# Filter out even numbers
filtered_set = {x for x in original_set if x % 2 != 0}

# Print the filtered set
print(filtered_set)


{1, 3, 5, 7, 9}


The set comprehension {x for x in original_set if x % 2 != 0} creates a new set that includes only the elements from the original set (original_set) for which the condition x % 2 != 0 is True.

This condition filters out all even numbers.

The resulting filtered_set will contain only the odd numbers from the original set.

27. Multiply all elements in a set by 2.

In [ ]:
# Original set
original_set = {1, 2, 3, 4, 5}

# Multiply all elements by 2
doubled_set = {x * 2 for x in original_set}

# Print the doubled set
print(doubled_set)


{2, 4, 6, 8, 10}


To multiply all elements in a set by 2,we can use a set comprehension.

The set comprehension {x * 2 for x in original_set} creates a new set by multiplying each element x from the original set (original_set) by 2.

The resulting doubled_set will contain the elements {2,4,6,8,10}, which are the original set elements multiplied by 2.

28. Create a set of random numbers.

In [ ]:
import random

# Set the seed for reproducibility (optional)
random.seed(42)

# Create a set of 5 random integers between 1 and 100 (inclusive)
random_set = {random.randint(1, 100) for _ in range(5)}

# Print the set of random numbers
print(random_set)


{4, 36, 15, 82, 95}


We import the random module.

We set the seed using random.seed(42) to make the random numbers reproducible (optional).

We use a set comprehension to generate a set (random_set) containing 5 random integers between 1 and 100 (inclusive).

Each time you run this code, you'll likely get a different set of random numbers due to the nature of randomness.

Setting the seed ensures that the sequence of random numbers is the same each time the script is run, which can be useful for reproducibility during development and testing.

29. Check if a set is empty.

In [ ]:
# Create an empty set
empty_set = set()

# Check if the set is empty
if not empty_set:
    print("The set is empty.")
else:
    print("The set is not empty.")


The set is empty.


We can check if a set is empty using a simple conditional statement.

The if not empty_set: condition checks whether the set is empty. If the set is empty, it will print "The set is empty." Otherwise, it will print "The set is not empty."

We can apply the same logic to any set by replacing empty_set with the name of your set variable.

30. Create a nested set (hint: use frozenset).

In [ ]:
# Create nested set using frozenset
nested_set = {frozenset({1, 2, 3}), frozenset({4, 5, 6}), frozenset({7, 8, 9})}

# Print the nested set
print(nested_set)


{frozenset({1, 2, 3}), frozenset({4, 5, 6}), frozenset({8, 9, 7})}


We can create a nested set using frozenset within a regular set.

We have a set nested_set that contains three frozenset objects.
    
Each frozenset represents an immutable set, and together they form a nested structure within the outer set.

31. Remove an element from a set using the discard method.

In [ ]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Remove an element using the discard method
my_set.discard(3)

# Print the modified set
print(my_set)


{1, 2, 4, 5}


The discard() method in Python is used to remove a specified element from a set.

If the element is not present in the set, the discard() method does nothing (no error is raised).

The discard(3) method is used to remove the element 3 from the set my_set.

The resulting set will be {1, 2, 4, 5}. If the set did not contain the element 3, the set would remain unchanged.

It's worth noting that there is also another method called remove(), which is similar to discard().

The key difference is that if you try to remove an element that is not present in the set using the remove() method, it will raise a KeyError.

32. Compare two sets.

In [ ]:
# Create a set
set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}

if set1 == set2:
    print("The sets are equal.")
else:
    print("The sets are not equal.")

The sets are not equal.


33. Create a set from a string.

In [ ]:
# Create a set from a string
my_string = "Gayatri"
my_set = set(my_string)

# Print the set
print(my_set)

{'G', 'r', 't', 'y', 'a', 'i'}


We can create a set from a string by using the set() constructor. This will create a set where each unique character in the string becomes an element of the set.

The string "Gayatri" is converted into a set, and the resulting set will contain unique characters from the string.

Keep in mind that sets are unordered collections, so the order of elements in the set may not be the same as the order in the original string.

Additionally, duplicate characters are automatically removed in a set, as sets only store unique elements.

34. Convert a set of strings to a set of integers.

In [ ]:
# Set of strings
set_of_strings = {"1", "2", "3", "4", "5"}

# Convert the set of strings to a set of integers
set_of_integers = {int(x) for x in set_of_strings}


# Print the set of integers
print(set_of_integers)


{1, 2, 3, 4, 5}


35. Convert a set of integers to a set of strings.

In [ ]:
# Set of integers
set_of_integers = {1, 2, 3, 4, 5}

# Convert the set of integers to a set of strings
set_of_strings = {str(x) for x in set_of_integers}

# Print the set of strings
print(set_of_strings)


{'1', '5', '4', '2', '3'}


We can convert a set of integers to a set of strings in Python using a similar approach with a set comprehension.

The set set_of_integers contains integers. The set comprehension {str(x) for x in set_of_integers} is used to create a new set, set_of_strings, where each integer element from the original set is converted to a string using the str() function.

The resulting set_of_strings will contain the strings '1', '2', '3', '4', and '5'.

36. Create a set from a tuple.

In [ ]:
# Tuple
my_tuple = (9,8,7,6,5)

# Create a set from the tuple
my_set = set(my_tuple)

# Print the set
print(my_set)

{5, 6, 7, 8, 9}


We can create a set from a tuple in Python using the set() constructor.

The tuple (9,8,7,6,5) is converted into a set using the set() constructor.

The resulting set, my_set, will contain the unique elements from the tuple.

37. Convert a set to a tuple.

In [ ]:
# Set
my_set = {9,8,7,6,5}

# Convert the set to a tuple
my_tuple = tuple(my_set)

# Print the tuple
print(my_tuple)

(5, 6, 7, 8, 9)


We can convert a set to a tuple in Python using the tuple() constructor.

The set {9,8,7,6,5} is converted into a tuple using the tuple() constructor. The resulting tuple, my_tuple, will have the same elements as the original set.

The order of elements in the tuple will be based on the order in which they are hashed and retrieved from the set, which might not be the same order in which they were originally added to the set due to the unordered nature of sets.

38. Find the maximum value in a set.

In [ ]:
# Set of numbers
my_set = {10, 5, 8, 20, 15}

# Find the maximum value in the set
max_value = max(my_set)

# Print the maximum value
print("Maximum value in the set:", max_value)

Maximum value in the set: 20


To find the maximum value in a set, we can use the max() function.

The max() function is applied to the set my_set to find the maximum value.

The result is then printed.

39. Find the minimum value in a set.

In [ ]:
# Set of numbers
my_set = {10, 5, 8, 20, 15}

# Find the minimum value in the set
min_value = min(my_set)

# Print the minimum value
print("Minimum value in the set:", min_value)


Minimum value in the set: 5


To find the minimum value in a set, we can use the min() function.

The min() function is applied to the set my_set to find the minimum value. The result is then printed.

As with the max() function, the min() function assumes the elements of the set are comparable (e.g., they are numbers). If the set contains non-comparable elements, you may encounter a TypeError.

40. Create a set from user input.

In [ ]:
# Get user input for a set of numbers
user_input = input("Enter a set of numbers separated by commas: ")

# Split the input string into a list of strings
numbers_str = user_input.split(',')

# Convert the list of strings to a set of integers
try:
    user_set = {int(num) for num in numbers_str}
    print("User input as a set:",user_set)
except ValueError:
    print("Invalid input. Please enter a valid set of numbers.")


Enter a set of numbers separated by commas:  7,3,7,8,3,9


User input as a set: {8, 9, 3, 7}


We  can create a set from user input by using the input() function to take input from the user and then converting the input into a set.

The user is prompted to enter a set of numbers separated by commas. The input is then split into a list of strings using split(',').

A set comprehension {int(num) for num in numbers_str} is used to convert the list of strings to a set of integers.

41. Check if the intersection of two sets is empty.

In [ ]:
# Example sets
set1 = {1, 2, 3}
set2 = {4, 5, 6}

# Check if the intersection is empty
intersection_result = set1.intersection(set2)

if not intersection_result:
    print("The intersection is empty.")
else:
    print("The sets have common elements.")


The intersection is empty.


We can check if the intersection of two sets is empty, by directly checking if the result of the intersection() method is an empty set.

The sets set1 and set2 do not have common elements, so the output will be "The intersection is empty."

If the sets had common elements, the output would indicate that they share elements.

42. Create a set of the first 5 Fibonacci numbers.

In [ ]:
# Function to generate the first n Fibonacci numbers
def generate_fibonacci(n):
    fibonacci_set = set()
    a, b = 0, 1
    for _ in range(n):
        fibonacci_set.add(a)
        a, b = b, a + b
    return fibonacci_set

# Create a set of the first 5 Fibonacci numbers
first_5_fibonacci_set = generate_fibonacci(5)

# Print the set
print("Set of the first 5 Fibonacci numbers:", first_5_fibonacci_set)


Set of the first 5 Fibonacci numbers: {0, 1, 2, 3}


We can create a set of the first 5 Fibonacci numbers using a loop to generate the sequence.

The generate_fibonacci function generates the first n Fibonacci numbers and adds them to a set.

The function is then called with n = 5 to create a set of the first 5 Fibonacci numbers.

The resulting set will be {0, 1, 2, 3, 5} since the first five Fibonacci numbers are 0, 1, 1, 2, and 3.


43. Remove duplicates from a list using sets.

In [ ]:
# Original list with duplicates
original_list = [1, 2, 3, 1, 2, 4, 5, 3]

# Remove duplicates using sets
unique_list = list(set(original_list))

# Print the list without duplicates
print("Original list:", original_list)
print("List without duplicates:", unique_list)


Original list: [1, 2, 3, 1, 2, 4, 5, 3]
List without duplicates: [1, 2, 3, 4, 5]


We  can remove duplicates from a list in Python by converting the list to a set (which automatically removes duplicates) and then converting it back to a list.

The set(original_list) part creates a set, removing any duplicate elements. Then, list() is used to convert the set back into a list.

The resulting unique_list will contain only the unique elements from the original list.

44. Check if two sets have the same elements, regardless of their count.

In [ ]:
# Example sets
set1 = {1, 2, 3, 4, 5}
set2 = {5, 4, 3, 2, 1}

# Check if sets have the same elements, regardless of order
if set1 == set2:
    print("The sets have the same elements, regardless of order.")
else:
    print("The sets do not have the same elements.")

# Alternatively, using set() constructor
if set(set1) == set(set2):
    print("The sets have the same elements, regardless of order (using set() constructor).")
else:
    print("The sets do not have the same elements (using set() constructor).")


The sets have the same elements, regardless of order.
The sets have the same elements, regardless of order (using set() constructor).


If you want to check if two sets have the same elements regardless of their count (i.e., they are equal sets), you can use the == operator or the set() constructor to create sets from both iterables and then compare them.

In both approaches, the sets set1 and set2 are considered equal because they contain the same elements, even though their order is different.

If you only want to check if the elements are the same regardless of their count, you can use the issubset() or issuperset() methods.

45. Create a set of the first `n` powers of 2.

In [ ]:
# Function to generate the first n powers of 2
def generate_powers_of_2(n):
    powers_of_2_set = set()
    for i in range(n):
        powers_of_2_set.add(2 ** i)
    return powers_of_2_set

# Create a set of the first 5 powers of 2
first_5_powers_of_2_set = generate_powers_of_2(5)

# Print the set
print("Set of the first 5 powers of 2:", first_5_powers_of_2_set)


Set of the first 5 powers of 2: {1, 2, 4, 8, 16}


We can create a set of the first n powers of 2 in Python using a loop.

The generate_powers_of_2 function generates the first n powers of 2 and adds them to a set using the add() method. The function is then called with n = 5 to create a set of the first 5 powers of 2.

The resulting set will be {1, 2, 4, 8, 16}, which are the first 5 powers of 2.

46. Find the common elements between a set and a list.

In [ ]:
# Example set and list
my_set = {1, 2, 3, 4, 5}
my_list = [3, 4, 5, 6, 7]

# Find the common elements using intersection() method
common_elements_method = my_set.intersection(my_list)

# Print the common elements
print("Common elements (using intersection()):", common_elements_method)



Common elements (using intersection()): {3, 4, 5}


47. Create a set of the first `n` triangular numbers.

In [ ]:
# Function to generate the first n triangular numbers
def generate_triangular_numbers(n):
    triangular_numbers_set = set()
    total = 0
    for i in range(1, n + 1):
        total += i
        triangular_numbers_set.add(total)
    return triangular_numbers_set

# Create a set of the first 5 triangular numbers
first_5_triangular_numbers_set = generate_triangular_numbers(5)

# Print the set
print("Set of the first 5 triangular numbers:", first_5_triangular_numbers_set)


Set of the first 5 triangular numbers: {1, 3, 6, 10, 15}


We can create a set of the first n triangular numbers in Python using a loop. The triangular number for a given positive integer n is the sum of the integers from 1 ton.

The generate_triangular_numbers function generates the first n triangular numbers and adds them to a set using the add() method. The function is then called with n = 5 to create a set of the first 5 triangular numbers.

The resulting set will be {1, 3, 6, 10, 15}, which are the first 5 triangular numbers.

48. Check if a set contains another set as a subset.

In [ ]:
# Example sets
set1 = {1, 2, 3, 4, 5}
set2 = {2, 4}

# Check if set2 is a subset of set1 using issubset() method
if set2.issubset(set1):
    print("set2 is a subset of set1.")
else:
    print("set2 is not a subset of set1.")

# Check if set2 is a subset of set1 using <= operator
if set2 <= set1:
    print("set2 is a subset of set1 (using <= operator).")
else:
    print("set2 is not a subset of set1 (using <= operator).")


set2 is a subset of set1.
set2 is a subset of set1 (using <= operator).


49. Create a set of alternating 1s and 0s of length `n`.

In [ ]:
# Function to generate a set of alternating 1s and 0s of length n
def generate_alternating_set(n):
    alternating_set = {1 if i % 2 == 0 else 0 for i in range(n)}
    return alternating_set

# Create a set of alternating 1s and 0s of length 8
alternating_set = generate_alternating_set(8)

# Print the set
print("Set of alternating 1s and 0s:", alternating_set)


Set of alternating 1s and 0s: {0, 1}


We can create a set of alternating 1s and 0s of length n in Python using a set comprehension.

The generate_alternating_set function uses a set comprehension to create a set of alternating 1s and 0s based on the index i. If i is even, it adds 1 to the set; otherwise, it adds 0. The function is then called with n = 8 to create a set of alternating 1s and 0s of length 8.

The resulting set will be {1, 0, 1, 0, 1, 0, 1, 0}.

50. Merge multiple sets into one.

In [ ]:
# Example sets
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set3 = {5, 6, 7}

# Merge sets using union() method
merged_set_method = set1.union(set2, set3)

# Print the merged sets
print("Merged sets (using union()):", merged_set_method)

Merged sets (using union()): {1, 2, 3, 4, 5, 6, 7}


We can merge multiple sets into one in Python using the union() method.

The code merges set1, set2, and set3 into a single set. The union() method.

The output will be a set containing all unique elements from the three sets: {1, 2, 3, 4, 5, 6, 7}.